### ISSUE TITLE
Error when finding opponent on the new Slippi dolphin build

### ISSUE THREAD

**Issue by SukeSJ** [bkacjios/m-overlay#10]
Hey i am getting this error when i find an opponent on the new Slippi build that uses Rollback netcode. It works fine when i open the game but it just stop working when i connect to an opponent. Here is the error
![Capture](https://user-images.githubusercontent.com/67334059/85430351-541f4c00-b580-11ea-8612-1bc4b67e9ea1.png)

**Comment by bkacjios** [comment]
Yeah, I am aware of this! Currently working on a fix.

**Comment by SukeSJ** [comment]
@bkacjios Oh okay. I just saw that some people don't get this error so i thought it was only for me and my friend. But if it is getting fixed then that is awesome. Thank you!!

**Comment by bkacjios** [comment]
I think one of the older versions without multiple game support would work.

The new netplay seems to use the memory space that has the game ID in it which ends up breaking it.

**Comment by SukeSJ** [comment]
@bkacjios Maybe i should try the Zelda Sheik hotfix one?

**Comment by bkacjios** [comment]
That version would probably work yeah, but just know that version is mostly for viewing replays, so the L and R sliders will be combined and pressing Z will show an A press as well.

**Comment by SukeSJ** [comment]
@bkacjios I tried but it wouldn't connect. I tried the Brawl Project+ and Melee Update one but that got the same error

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.0.5

I just made a quick little release that seems to work. Launch the overlay, press escape and enable "Slippi Netplay." I only had time to test it once since I need to go for a few hours, so let me know if there's any issues.

**Comment by SukeSJ** [comment]
@bkacjios Awesome!! It works perfectly now. Only thing i saw was that the colour of the Z button wasn't completely filled in. But that is just nitpicking xD. I will keep on testing it and if i find anything that either isn't working or doesn't look right. I will let you know!
![Capture](https://user-images.githubusercontent.com/67334059/85443352-75d4ff00-b591-11ea-85e0-567b9c97047c.png)

**Comment by bkacjios** [comment]
That's a part of the texture. Lol. It's supposed to look like the little nub on the actual Z button.

**Comment by SukeSJ** [comment]
@bkacjios Ahh okay i get what you mean now. I didn't see that before so i thought it was bugged xD. Thank you so much for the fixed update tho! That is awesome! again. If i find anything. I will let you know!

**Comment by bkacjios** [comment]
I am curious about what happens when your game switches to player 2 when playing. Does it continue to work despite the overlay being on port 1 but the game having you on port 2?

**Comment by SukeSJ** [comment]
@bkacjios I tried to test it out with my friend and it seems that whoever searches for another first is port 1. So in a Direct match. That wouldn't matter. Unranked however i think it will. Since you basically disconnect and reconnect to another opponent (unless you play the same person multiple times). So Unranked with the same person multiple times and Direct matches will make it stay the same port. Unranked with several people and or joining back in on a Direct connection would change the port where you need to change the overlay as well. Not the best way to playtest. But i hope it answers some questions

**Comment by bkacjios** [comment]
Ah cool, good to know. I'll have to try and figure out a way to detect what port you are currently using and automatically switch to it.

**Comment by SukeSJ** [comment]
@bkacjios If that would be a button for auto detection on the ports would be cool. Tho some might use the input display to show both your inputs and the opponents inputs (Now that, that is possible). So having it toggleable would be perfect but not mandatory :D

**Comment by bkacjios** [comment]
Yeah, it will definitely be an extra option that will be available when "Slippi Netplay" is enabled.

**Comment by bkacjios** [comment]
I added some options to enable port detection using your slippi display name

![Slippi settings](https://i.imgur.com/siiAH3z.png)
