### ISSUE TITLE
Read in-game RNG for song selection

### ISSUE THREAD

**Issue by ribbanya** [bkacjios/m-overlay#100]
I know this is an extremely niche use case, but my friends and I all use the same music library (same songs with same weights). Would it be possible to use the in-game random number generator (read-only) instead of `math.random`?

Unless I'm mistaken, this should sync the music choices in Slippi without need for any netcode in M'Overlay. I suppose it would desync when a player skips a song or two players have different loop settings from each other, but it should, in theory, sync at every scene load.

**Comment by bkacjios** [comment]
Done. Slippi's random seed will now be used. This should sync the tracks between clients, so long as your playlists match identically.

**Comment by ribbanya** [comment]
Wow, that was fast. Thank you!

I'll test it when I get a chance. How often is `memory.hook` triggered?

**Comment by bkacjios** [comment]
Once every frame.

**Comment by ribbanya** [comment]
This works absolutely perfectly. Thank you so much! 💯
