### ISSUE TITLE
Music occasionally desyncs when using Slippi's seed

### ISSUE THREAD

**Issue by ribbanya** [bkacjios/m-overlay#101]
This can cause desyncs when relying on the Slippi seed to play music.

The issue stems from the order of [`getDirectoryItems`](https://love2d.org/wiki/love.filesystem.getDirectoryItems) being undefined:
> The table is not sorted in any way; the order is undefined.

The songs should be sorted in order of a deterministic factor (probably just filename or full path) before being traversed and added to the playlist table.

https://github.com/bkacjios/m-overlay/blob/cc156be220c70f3888419e592feea66a13a4fad9/source/music.lua#L365

[Here](https://stackoverflow.com/a/15706820/5880994) is a way I found to sort tables. It should be enough to wrap `ipairs(spairs(files, [filename order function]))`.

 I don't mind doing a PR for this, but I'm not familiar with LOVE so I'd have to set up a dev environment.

**Comment by ribbanya** [comment]
Depending on when the seed is actually set, relative to when the files are loaded, it may make more sense to insert the songs in sorted order into the playlist and then play them in random order.

**Comment by bkacjios** [comment]
Ah, makes sense. Yeah, I can add just add them alphabetically at the start, then use the seeded RNG to shuffle later.

**Comment by bkacjios** [comment]
[m-overlay-x64-installer.zip](https://github.com/bkacjios/m-overlay/files/7023593/m-overlay-x64-installer.zip)
[m-overlay-x64-portable.zip](https://github.com/bkacjios/m-overlay/files/7023594/m-overlay-x64-portable.zip)

Mind giving this build a try to see if this helps?

**Comment by ribbanya** [comment]
I can test with a friend soon.

I think that, in order to avoid the race condition entirely, the playlist should be sorted and reshuffled when the seed is hooked. Then you could remove the sort at load time (since it's irrelevant if there's no Slippi seed).
https://github.com/bkacjios/m-overlay/blob/8f89dda3e2a999779476d1373353ae083c17e252/source/music.lua#L206-L208

So something like this:
```lua
memory.hook("slippi.rng_offset", "Sync RNG Seed", function(seed)
	math.randomseed(seed)
	table.sort(music.PLAYLIST)
	-- shuffle logic
end)
```

That way there's no time spent sorting if there's no Slippi seed, and if there is, it's always shuffled according to the seed.

**Comment by bkacjios** [comment]
I don't think this should be necessary. The slippi_rng value gets set the moment the VS screen becomes visible. The tracks aren't loaded until the stage ID gets updated, which is when the VS screen ends.

**Comment by bkacjios** [comment]
[m-overlay-x64-installer.zip](https://github.com/bkacjios/m-overlay/files/7024147/m-overlay-x64-installer.zip)
[m-overlay-x64-portable.zip](https://github.com/bkacjios/m-overlay/files/7024148/m-overlay-x64-portable.zip)

I made one last final change. When a match ends, the seed value gets set back to 0. I decided to just ignore that case, and use the previous matches seed. This should cause the menu music to sync up as well.

I also added a debug message that you can use to see if two clients are in sync. I flush the first 8 random numbers when the seed is changed and output as a hex value.

`[DEBUG - 17:17:11] [RANDOM] Flushing random of initial values (0x6644D2C98E2B6418)`

You can compare that value in parenthesis with your friend, and if they match, you are in sync.

**Comment by ribbanya** [comment]
These are great changes, thank you.

We'll test it out in the next couple hours.

**Comment by ribbanya** [comment]
Okay, so whenever the seed is successfully read and output to the log, we're in sync. No desyncs when the seed is the same.

The problem is that on my machine (but not my friend's, for whatever reason), a match will **sometimes** start and not output a new seed. My friend receives a new seed every match. We can't determine a pattern to this, it seems very unpredictable.

It's very strange, because M'Overlay is consistently able to read other hooks, like stage changes and match ending and stuff. This appears to be the only hook that gets randomly "dropped."

I'm on Windows 10 x64 and they're the same but using Bootcamp.

**Comment by bkacjios** [comment]
Hmm.. I wonder if the slippi rng_offset value is only set if the player isn't the host.. I'll have to do some investigating into the inner workings of the slippi online assembly.

**Comment by ribbanya** [comment]
Upon further testing, looks like only the winner gets a new `rng_offset`. I set `slippi.rng_offset.debug = true` and it's consistent with the flush log being printed.

**Comment by ribbanya** [comment]
Seems like the first time a connection is made, the seed is always transmitted to both clients.

So if we could set the seed once per matchmaking connection and then never again, it will stay in sync.

If one person skips a song, and then at any point later on the other person skips a song, the songs will resync.

**Comment by bkacjios** [comment]
So what I think is happening is the loser of the match actually becomes the host for the next match. The loser then sends their RNG seed to the winner to sync the two games up. The slippi pointer doesn't get updated for the loser, probably because they already have the correct RNG seed.

**Comment by ribbanya** [comment]
That's what we were thinking, yeah.

**Comment by ribbanya** [comment]
I believe this commit (890c17619d7cdb65b4d878a792781179dabb73e9) should work but I can't test it until later.

**Comment by ribbanya** [comment]
Actually nevermind that commit. The Melee 1.02 seed is at `0x804D5F90` (Googling it even produces [some interesting results](https://www.google.com/search?q=804D5F90)). This should let us use the in-game seed regardless of what Slippi does with it.

The one thing I have to look into is that Slippi seems to purposely desync the seed between matches so that players random different characters.
https://github.com/project-slippi/slippi-ssbm-asm/blob/9c36ffc5e4787c6caadfb12727c5fcff07d64642/Online/Slippi%20Online%20Scene/main.asm#L610

**Comment by ribbanya** [comment]
I tried a few different things that didn't work. What I'm looking at now is this:

https://github.com/project-slippi/slippi-ssbm-asm/blob/9c36ffc5e4787c6caadfb12727c5fcff07d64642/Online/Core/InitOnlinePlay.asm#L212-L233

This is where the initial seed is pulled by Slippi and pushed into the game's RNG seed. In order to properly access the value, we need to read register 13 from Dolphin. Currently there don't appear to be any functions in M'Overlay that read Dolphin registers, so I'm looking into how to do that.

**Comment by bkacjios** [comment]
I already have M'Overlay reading that value from the correct memory space.

```lua
-- https://github.com/project-slippi/slippi-ssbm-asm/blob/9c36ffc5e4787c6caadfb12727c5fcff07d64642/Online/Online.s#L29
local CSSDT_BUF_ADDR = 0x80005614

game.memorymap[CSSDT_BUF_ADDR] = {
	type = "pointer",
	name = "slippi",
	struct = {
		-- https://github.com/project-slippi/slippi-ssbm-asm/blob/9c36ffc5e4787c6caadfb12727c5fcff07d64642/Online/Online.s#L253
		[0x000] = {
			type = "pointer",
			--name = "slippi_ptr",
			struct = {
				[0x00] = { type = "u8", name = "connection_state" },
				[0x01] = { type = "u8", name = "local_player.ready" },
				[0x02] = { type = "u8", name = "remote_player.ready" },
				[0x03] = { type = "u8", name = "local_player.index", debug = true },
				[0x04] = { type = "u8", name = "remote_player.index" },
				[0x05] = { type = "u32", name = "rng_offset", debug = true },
				[0x09] = { type = "u8", name = "delay_frames" },
				[0x0A] = { type = "u8", name = "local_player.chatmsg_id" },
				[0x0B] = { type = "u8", name = "opponent.chatmsg_id" },
				[0x0C] = { type = "u8", name = "chatmsg.index" },
				[0x0D] = { type = "u32", name = "vs.left_names" },
				[0x11] = { type = "u32", name = "vs.right_names" },
				[0x15] = { type = "data", len = 31, name = "local_player.name" },
				[0x34] = { type = "data", len = 31, name = "players.1.name" },
				[0x53] = { type = "data", len = 31, name = "players.2.name" },
				[0x72] = { type = "data", len = 31, name = "players.3.name" },
				[0x91] = { type = "data", len = 31, name = "players.4.name" },
				[0xB0] = { type = "data", len = 63, name = "opponent.name" },
				[0xEF] = { type = "data", len = 10, name = "players.1.code" },
				[0xF9] = { type = "data", len = 10, name = "players.2.code" },
				[0x103] = { type = "data", len = 10, name = "players.3.code" },
				[0x10D] = { type = "data", len = 10, name = "players.4.code" },
				[0x117] = { type = "data", len = 241, name = "error_msg" },
			}
		},
	}
}
```

ODB_RNG_OFFSET is `[0x05] = { type = "u32", name = "rng_offset", debug = true },`

**Comment by bkacjios** [comment]
I was also experimenting with the RNG seed myself last night too. I think I may have a solution, but it would need testing.

`game.memorymap[0x804D5F90] = { type = "u32", name = "rng.seed" }`

**Comment by bkacjios** [comment]
[m-overlay-x64-installer.zip](https://github.com/bkacjios/m-overlay/files/7026152/m-overlay-x64-installer.zip)
[m-overlay-x64-portable.zip](https://github.com/bkacjios/m-overlay/files/7026153/m-overlay-x64-portable.zip)

I made it so whenever a stage is loaded, it uses the game's internal RNG seed. Slippi should have done it's magic by that point and sync'd up the two clients.

**Comment by ribbanya** [comment]
Yeah, that desyncs because it changes every frame and can't reliably be polled at the same time by both clients.

I have a working solution, I think.
