### ISSUE TITLE
Error running on Ubuntu

### ISSUE THREAD

**Issue by itsonlyMiRE** [bkacjios/m-overlay#105]
**Describe the bug**
Program blue screens when running with love from CLI.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Dolphin Version: n/a

**To Reproduce**
1. Install love and download .love file for m-overlay
2. Run `love-11.3 m-overlay-x64.love` OR `love m-overlay-x64.love` in command line, or double click from file manager
3. See blue screen
![image](https://user-images.githubusercontent.com/50085297/130508922-f180c895-95e3-4119-9459-27e5c1e8510b.png)

Let me know if you need any other information

**Comment by bkacjios** [comment]
[m-overlay-x64.zip](https://github.com/bkacjios/m-overlay/files/7034518/m-overlay-x64.zip)

Whoops. Mind giving this a try?

**Comment by itsonlyMiRE** [comment]
This worked!

**Comment by bkacjios** [comment]
Thanks for testing!
