### ISSUE TITLE
Have port constantly showing

### ISSUE THREAD

**Issue by SukeSJ** [bkacjios/m-overlay#11]
Not an issue. But i don't know how to contact otherwise. Would be cool to have a toggle so it says what port you are at all times. Then when people stream. People wouldn't have to ask (what character are you?)

**Comment by bkacjios** [comment]
I can add that! I was actually thinking about showing the stock icon for what character you are playing as well! Would that be something you would like too?

**Comment by bkacjios** [comment]
You can just make a new issue if you have any requests. Issues don't have to be exclusively bugs or problems!

**Comment by SukeSJ** [comment]
@bkacjios Okay awesome. I will be sure to do so if i have any requests in the future! Have a wonderful day

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.1.1

Here's what you requested!
