### ISSUE TITLE
"Adaptive" loop setting?

### ISSUE THREAD

**Issue by ribbanya** [bkacjios/m-overlay#114]
I was thinking it'd be cool if we could determine whether the in-game timer is counting down or up (regular match vs. Uncle Punch events, infinite time matches, vanilla training mode, etc.) and loop when it's a regular match but use a playlist when the timer is infinite.

This could just be another option in the "Music Loop Mode" slider.

I'd be happy to implement it, but what do you think of it as a feature?

**Comment by bkacjios** [comment]
Sounds good to me. I actually know how to determine the direction the timer is going. I believe this is a flag set in the startmelee struct. I may have to add it and document it for you, but it should be useful for this.

**Comment by ribbanya** [comment]
Do you think checking for stock battle would just be better?

**Comment by bkacjios** [comment]
I think all you'd really have to do is check if the timer is counting up. If it is, it's an infinite match.

**Comment by ribbanya** [comment]
Uncle Punch said this on Discord, by the way.

> https://github.com/akaneia/m-ex/blob/master/MexTK/include/match.h#L50
> its dictated by these bits in the MatchInit struct
> https://github.com/akaneia/m-ex/blob/master/MexTK/include/match.h#L11-L14
> 2 for count down, 3 for count up
> can find the static MatchInit @ mem addr 0x8046DB68

Apparently it can be frozen, hidden, down, or up.

**Comment by bkacjios** [comment]
Yeah, I have that struct mapped out already.

https://github.com/bkacjios/m-overlay/blob/5034cacde88d0352f9a1da32513f440fef6df855/source/modules/games/GALE01-2.lua#L241

I guess you actually want `match.flags.other`

**Comment by ribbanya** [comment]
What's the difference between `0x80480530` and `0x8046DB68`?

**Comment by bkacjios** [comment]
Not sure what `0x8046DB68` is.

**Comment by ribbanya** [comment]
I'll see if there's any difference. Probably just two places in memory with the same data.

**Comment by bkacjios** [comment]
Seems so. I think one of these is only available when actually in a match, and the other is available before hand? I don't really remember.

**Comment by bkacjios** [comment]
Okay, actually, `8046DB68` is missing the PlayerData at the end. I remember now.

**Comment by ribbanya** [comment]
Yeah, I set breakpoints on them and `80480530` gets copied into `8046DB68`, so I'll just use the former.

**Comment by ribbanya** [comment]
Upon further inspection, `8046DB68` is populated during event matches (needed for Uncle Punch) while `80480530` seems to only work during VS. Mode.

**Comment by bkacjios** [comment]
Well, I figured out how to calculate the different flag values for you, so hopefully this helps.

```lua
local startmatch_addr = 0x8046DB68

local startmatch_struct = {
	[0x00] = { type = "u8", name = "match.flags.game" },
	--[[
		TIMER = bit.band(flags, 3)

		0: TIMER_FROZEN
		1: TIMER_HIDDEN
		2: TIMER_COUNT_DOWN
		3: TIMER_COUNT_UP

		HUDPOS = bit.band(bit.rshift(flags, 2), 7)

		0: MATCH_HUDPOS_NONE
		1: MATCH_HUDPOS_ONE
		2: MATCH_HUDPOS_TWO
		3: MATCH_HUDPOS_THREE
		4: MATCH_HUDPOS_FOUR
		5: MATCH_HUDPOS_SIX
		6: MATCH_HUDPOS_UNK
		7: MATCH_HUDPOS_FOURCOMPACT

		MATCH = bit.band(bit.rshift(flags, 5), 7)

		0: MODE_TIME
		1: MODE_STOCK
		2: MODE_COIN
		3: MODE_BONUS
	]]
```
