### ISSUE TITLE
v1.1.5 detect port w/ Slippi 2.1.1

### ISSUE THREAD

**Issue by mturnell001** [bkacjios/m-overlay#12]
In Unranked Mode, if I am randomly assigned to player 2, the first game the overlay will properly detect that I am P2 and display my inputs. If I continue with more games with the same opponent, it will "detect" that I am P1 and display my opponent's inputs. This happens consistently. Unknown if it happens w/ Direct Match.

**Comment by bkacjios** [comment]
I see. I think I know why this happens. I can get a fix out for you in a bit.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.1.6

This should fix the issue. I couldn't test it though.

**Comment by trellium** [comment]
Tried the new fix today, did not work on port switching either. made a new issue, but if this is the same feel free to delete other one.
