### ISSUE TITLE
[Game Request] NARJ Majora's Mask VC (Japanese Version)

### ISSUE THREAD

**Issue by Ohmacide86** [bkacjios/m-overlay#120]
It would be really cool if you could add support for the JP VC version of MM, I tried renaming the NARE.lua to NARJ but I could not find what the address in the file was reading from using the Speedrunning practice rom KZ which has an option for reading all the memory addresses in game, so I assumed it must be looking else where. I would be happy to send over a .wad of the JP version if you need it or look up the address if you know where it should be.

Thank you 
Ohma`

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v2.0.2a
