### ISSUE TITLE
Metroid Prime 2: Echoes Randomizer not found in game directories

### ISSUE THREAD

**Issue by illiaster123** [bkacjios/m-overlay#123]
I've used m-overlay when playing Metroid Prime (Randomized and original) and it works fine.
My issue is when I open any randomized Copy of Metroid Prime 2: Echoes, I receive this error in the debug console window:

[ERROR - 20:57:48] [DOLPHIN] module 'games.G2ME1R-0' not found:
        no field package.preload['games.G2ME1R-0']
        no 'games/G2ME1R-0' in LOVE game directories.
        no file 'games/G2ME1R-0' in LOVE paths.
        no file '.\games\G2ME1R-0.lua'
        no file 'D:\Emulators\Dolphin\Tools\M'overlay\lua\games\G2ME1R-0.lua'
        no file 'D:\Emulators\Dolphin\Tools\M'overlay\lua\games\G2ME1R-0\init.lua'
        no file '.\games\G2ME1R-0.dll'
        no file 'D:\Emulators\Dolphin\Tools\M'overlay\games\G2ME1R-0.dll'
        no file 'D:\Emulators\Dolphin\Tools\M'overlay\loadall.dll'
        no file '.\games.dll'
        no file 'D:\Emulators\Dolphin\Tools\M'overlay\games.dll'
        no file 'D:\Emulators\Dolphin\Tools\M'overlay\loadall.dll'
stack traceback:
        [C]: at 0x7ffae8dc6420
        [C]: in function 'xpcall'
        modules/memory/init.lua:449: in function 'loadGameScript'
        modules/memory/init.lua:511: in function 'findGame'
        modules/memory/init.lua:579: in function 'updatememory'
        modules/memory/init.lua:551: in function 'update'
        main.lua:211: in function 'update'
        main.lua:681: in function <main.lua:661>
        [C]: in function 'xpcall'
        [string "boot.lua"]:802: in function <[string "boot.lua"]:769>
        
        Not certain if there is anything on my end or if this is indeed a bug report, but I thought I'd at least submit an issue since I noticed the randomizer is listed as compatible. 
        Thanks!

**Comment by bkacjios** [comment]
Looks like they changed the GAMEID for the randomizer.

**Comment by illiaster123** [comment]
yea, sounds about right. Sorry about that, I didn't know of any specific reason so I thought I'd bring it to the attention. Thanks for the response though. I'll probably ask about it in their server.

**Comment by bkacjios** [comment]
So I reviewed how the ranomdizer works. It appears you enabled a "menu mod" or something which ends up changing the GAMEID to end in 1R rather than 0R. I guess I have to support this option too lol.

https://github.com/randovania/randovania/blob/f10e3d2780f18de604b246ebe44390f2afc8c778/randovania/games/patchers/claris_patcher_file.py#L437-L439

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v2.0.3a
