### ISSUE TITLE
M'Overlay | Invalid Permissions on Linux

### ISSUE THREAD

**Issue by SillyStudios25** [bkacjios/m-overlay#125]
Every time i open M'Overlay, i see the following message as the title of the window:
"M'Overlay - Invalid Permissions... (Port 1)"

I play on Pop! OS and my Slippi version is 2.1.5
Currently i have no idea on how to reproduce the bug, or even how it works.
What it does is it doesn't detect Slippi, Dolphin or the game instance, meaning music doesn't play and the controller inputs aren't being displayed

![](https://cdn.discordapp.com/attachments/854294091628806157/897034367891816448/Screenshot_from_2021-10-11_19-13-09.png)

Debug Console Output:
`
[DEBUG - 19:07:42] Love2D 11.3.0 - Mysterious Mysteries
[DEBUG - 19:07:42] Lua 5.1 (LuaJIT 2.1.0-beta3)
[DEBUG - 19:07:42] M'Overlay (2.0.3a)
`
If you need any other information I will provide it

**Comment by SillyStudios25** [comment]
The command doesn't work:
`Failed to set capabilities on file `/usr/bin/love-11.3' (No such file or directory)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
`
The only mention of love in /usr/bin is the love file. There is no folder with the name llove
Also i tried Ubuntu: it also doesn't work there either.

**Comment by SillyStudios25** [comment]
Forgot to mention i reset my computer. I'll try and get the love-11.3 file. Sorry for the inconvenience.

**Comment by zzzachzzz** [comment]
Old issue, just leaving my confirmed solution for future viewers. I ran into the same issue on Debian, after installing love with `sudo apt install love`.

I followed a couple symlinks:
```
$ ls -l $(which love)
lrwxrwxrwx 1 root root 22 Jun  9  2022 /usr/bin/love -> /etc/alternatives/love

$ ls -l /etc/alternatives/love
lrwxrwxrwx 1 root root 18 Jun  9  2022 /etc/alternatives/love -> /usr/bin/love-11.4

$ ls -l /usr/bin/love-11.4
-rwxr-xr-x 1 root root 4364208 Jun  9  2022 /usr/bin/love-11.4
```
And then finally set permissions on that file being pointed to successfully:
```
$ sudo setcap cap_sys_ptrace=eip /usr/bin/love-11.4
```

**Comment by amphyvi** [comment]
On Love 11.5, the above worked for me too, except with the appropriate version number

```bash
$ sudo setcap cap_sys_ptrace=eip /usr/bin/love-11.5
```

Could the setup guide be updated for this, @bkacjios?
