### ISSUE TITLE
Support for Rivals of Aether

### ISSUE THREAD

**Issue by Taktaagic** [bkacjios/m-overlay#136]
This has probably been asked before, so I'm sorry if I'm just adding onto the pile of similar questions, but I'm curious if this will get support for games like Rivals of Aether. I'm assuming that it might not be possible, since I have to use a program to get the GameCube controller working on ROA, but I've just been wondering about if it is a possibility.

Also I have no clue if I'm using this right, since I've never used GitHub before

**Comment by bkacjios** [comment]
It's possible, just not feasible. I'd have to reverse engineer ROA and find where the input values are stored in memory. This is what I already do for dolphin, but the whole program is based around it only supported Dolphin, so it's sort of out of the scope of this project. You'd be better off getting an arduino and making a NintendoSpy based input viewer.

https://github.com/jaburns/NintendoSpy/blob/master/docs/tutorial-gamecube.md
