### ISSUE TITLE
libcap not found on Fedora 34/35

### ISSUE THREAD

**Issue by dhalucario** [bkacjios/m-overlay#138]
**Describe the bug**
libcap is not found even though it is installed.

**Desktop (please complete the following information):**
 - OS: Fedora 34/35
 - Dolphin Version: -

**To Reproduce**
1. Open m-overlay
2. See: Error: modules/memory/linux.lua:24: libcap.so: cannot open shared object file: No such file or directory

**Expected behavior**
I expected it to find my installed version of libcap.so to be found.
Its located at `usr/lib64/libcap.so.2`

**Additional context**
You can temporarily fix this by running the following command:
`sudo ln -s /usr/lib64/libcap.so.2 /usr/lib64/libcap.so`

**Comment by bkacjios** [comment]
That seems more like a distribution issue. I'm not familiar with fedora, but the system should have already created a "libcap.so" that points to the latest version for compilation/linker purposes.

**Comment by dhalucario** [comment]
Alright, I will ask the maintainers of the package then.

**Comment by bkacjios** [comment]
It may also be that the development package provides the symlink needed. `libcap-devel`
