### ISSUE TITLE
Dolphin not Hooking

### ISSUE THREAD

**Issue by ikohthe** [bkacjios/m-overlay#14]
Overlay is able to hook to all other versions of Dolphin I have except the newest Slippi online. I have rollback/netplay ticked. The config for the slippi online dolphin is identical to the other dolphin versions that work. I love using your beautiful creation on my other dolphin builds, and I would love to also be able to use it for slippi online :)

**Comment by bkacjios** [comment]
What OS are you on? Mine hooks fine on windows with Slippi 2.2.0

**Comment by ikohthe** [comment]
> What OS are you on? Mine hooks fine on windows with Slippi 2.2.0

I am on windows 10 using Slippi 2.2.0

**Comment by ikohthe** [comment]
I tried redownloading the overlay and had the same issue. I might go and redownload slippi to see if that works

**Comment by bkacjios** [comment]
Make sure you don't have any other instances of dolphin open.

If you still can't hook, can you enable the debug console and paste the output of it here?

You can enable the console by right clicking on the shortcut, go to properties, and add `--console` to the target path box.

![Debug Console](https://i.imgur.com/fxoyFc4.png)

**Comment by ikohthe** [comment]
[INFO  - 17:35:24] Load: C:/Users/Julien/AppData/Roaming/m-overlay/clones.lua

that is all i got also reinstalling the slippi online didnt fix the issue

**Comment by bkacjios** [comment]
Have you renamed the exe at all? It should be called `Dolphin.exe` ? If it was renamed it could break it. That's the only thing I can think of.

**Comment by ikohthe** [comment]
Hahaha that was exactly it!! I had renamed it something stupid to differentiate between the twenty other dolphin apps I have. Thanks for the easy fix!!!! Love your stuff :)

**Comment by bkacjios** [comment]
Nice! Glad we could figure this out. You can remove the `--console` thing if you would like to now. :)
