### ISSUE TITLE
Multiple Game Support Request for the Scooby-Doo Gamecube Games

### ISSUE THREAD

**Issue by DeathMaster001** [bkacjios/m-overlay#143]
Currently the only supported Scooby-Doo game that works with m-overlay is Scooby-Doo! Night of 100 Frights NTSC-U 1.0

My request is to add support for:

Scooby-Doo! Night of 100 Frights NTSC v1.1
Scooby-Doo! Unmasked NTSC v1.0
Scooby-Doo! Mystery Mayhem NTSC 1.0

Optionally, I would love to see the various languages/PAL releases for the above game's included sometime in the far future

Scooby-Doo! Night of 100 Frights PAL v1.0
Scooby-Doo! La Nuit des 100 Frissons PAL v1.0 (French n100f)
Scooby-Doo! nacht der 100 schrecken NTSC v1.0 (n100f German)
Scooby-Doo! Unmasked PAL v1.0
Scooby-Doo! Mystery Mayhem PAL v1.0

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v2.0.3i
