### ISSUE TITLE
Linux - Error on Start

### ISSUE THREAD

**Issue by git-iso** [bkacjios/m-overlay#15]
Using Love 11.3 from the Manjaro repo and the m-overlay 1.30 .love , I get a crash on startup with `sudo love m-overlay-x64.master-96.love`. `sudo setcap cap_sys_ptrace=eip /usr/bin/love` and running the file crashes as well.

![2020-07-21_09-38](https://user-images.githubusercontent.com/46284404/88061809-ff96ce80-cb35-11ea-925a-8c117dbea41c.png)

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/download/v1.3.0/m-overlay-x64.master-97.love

I uploaded a fix for this. Sorry about that.

**Comment by git-iso** [comment]
Thanks!
