### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Toffee64** [bkacjios/m-overlay#152]
**Describe the bug**
Upon starting the application, the window only shows a blank screen. Hitting escape turns the window from a blank black screen to a blank white screen. This persists throughout opening Dolphin and starting Slippi.

**Desktop (please complete the following information):**
 - OS: Windows
 - Dolphin Version: Faster Melee - Slippi (2.4.0)

**To Reproduce**
1. Open application
2. Issue occurs and Persists throughout Dolphin processes

**Expected behavior**
I expected the window for the application to open and show the "Waiting for Dolphin" screen. Upon opening Dolphin and starting Slippi, I expected it to show inputs, but the blank screen persists.

**Screenshots**
![Screenshot (118)](https://user-images.githubusercontent.com/84923628/182268924-2bf91446-6db0-4d77-933a-4a31fe35202c.png)
![Screenshot (122)](https://user-images.githubusercontent.com/84923628/182268935-dbe45342-7e2f-4619-953a-8d0357303b42.png)
![Screenshot (123)](https://user-images.githubusercontent.com/84923628/182268939-e85dcfb5-4807-4c51-862e-ccd2125010ff.png)

**Debug console output**
```
Unfortunately, I am unable to access the debug console output as attempting to open the menu leads to a blank white screen with nothing to select.
```
**Additional context**
I'm not sure what changed. I've updated my graphics drivers through Radeon Adrenalin regularly, but this hasn't caused an issue in the past.
PC Specs:
Ryzen 9 3900X
Radeon 6900 XT

**Comment by bkacjios** [comment]
The console log can be found in `%APPDATA%/m-overlay`

**Comment by Toffee64** [comment]
Perfect, thanks! I think I found it:
[DEBUG - 21:52:34] Love2D 11.4.0 - Mysterious Mysteries
[DEBUG - 21:52:34] Lua 5.1 (LuaJIT 2.1.0-beta3)
[DEBUG - 21:52:34] M'Overlay (2.0.3i)

**Comment by haruhooves** [comment]
hi toffe, I also had the same problem after updating the amd adrenalin video driver, I updated it to version 22.7.1 and from there the program only gave me the black and white screen like you, what worked for me was to install a previous version of the video driver, install 22.5.2 and the program worked again, I think the problem may be an incompatibility with the video drivers of the most current version, maybe the solution is to wait for get a patch or a new update of m'overlay or video drivers,The following screenshot shows the version that I have, which is 22.5.2, and next to it, it asks me to update to version 22.7.1. If I do this, the program will fail me again, as it did for you.
![imagen_2022-08-03_022407893](https://user-images.githubusercontent.com/110523919/182548882-fc221930-be8a-4654-8468-ff8e99e145ff.png)

**Comment by haruhooves** [comment]
I have slippy dolphin in version 2.4.0 and M'overlay in 2.0.3i, so I doubt that the problem was that both programs are out of date, but I support more the theory that it is a problem with the latest update of video drivers
![imagen_2022-08-03_022930345](https://user-images.githubusercontent.com/110523919/182549845-834fadec-6c1c-4132-98b1-f3179ff3115b.png)

**Comment by Toffee64** [comment]
Hi haruhooves! Thanks for your comments. They were very informative and it's nice to see that there is a solution if I want to get M'Overlay working again! For the time being if I want to see the inputs of replays I can use my laptop and hope an update of the video drivers or M'Overlay fixes the issue in the future. Thanks again!

**Comment by bkacjios** [comment]
https://github.com/love2d/love/issues/1821

When this gets fixed upstream I'll be sure to update to it.

**Comment by bkacjios** [comment]
New AMD driver update specifically fixes this issue.

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-8-1

> Games based on LOVE2D™ engine may be rendered incorrectly.
