### ISSUE TITLE
M overlay is black I can't access settings it occurs even when dolphin is open

### ISSUE THREAD

**Issue by Hexaroot** [bkacjios/m-overlay#156]
**Describe the bug**
M Overlay is black can't access settings or anything even with dolphin open 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Dolphin Version: [e.g. Dolphin 5.0-15993]

**Screenshots**
https://i.imgur.com/JD6Wc6P.png
https://i.imgur.com/tDUWckO.png

**Debug console output**
Can't open it because can't access settings.

**Additional context**
I tried reinstalling the program but it had the same bug I have no idea why its doing this but can someone figure it out?

**Comment by bkacjios** [comment]
You can access the log file in `%appdata%/m-overlay`

![image](https://user-images.githubusercontent.com/3247233/197400801-b73cdb1c-0e88-486d-93a0-fe40e9916fd1.png)

**Comment by bkacjios** [comment]
This seems similar to issue #152

Check to see if your video driver needs an update.
