### ISSUE TITLE
[SSBM Slippi] Music for Ranked menu

### ISSUE THREAD

**Issue by Cherryello** [bkacjios/m-overlay#158]
As the title says. If it can be helpful, this is my console.log after two sets of ranked matches. Thank you!
https://pastebin.com/WvBHjqzT

**Comment by bkacjios** [comment]
Aha, thanks for the logs. Looks like the ranked menu is a new, unhanded, screen.

Thanks! Will try to get this fixed by tomorrow.

:)

**Comment by bkacjios** [comment]
[m-overlay-x64-portable.zip](https://github.com/bkacjios/m-overlay/files/10223358/m-overlay-x64-portable.zip)

Mind giving this a try? I don't have the means of testing it.

If it works I'll bundle up the installer and make a release.

**Comment by Cherryello** [comment]
Thank you for the quick reply and sorry for my late one, I'm from Europe and there was the night in between!
By the way it works, the ranked menu doesn't have its own music but it uses the menu ones. I initially wanted different music for the ranked menu, but maybe it would have been too messy, so I like it this way. Thank you!

**Comment by bkacjios** [comment]
Yeah, doing things like treating that specific screen as something other than the menu is possible, just messy. It's much easier to treat it as a menu and not have the music stop.

So it's all good then? I'll push out a release.

**Comment by Cherryello** [comment]
All good! It works like a charm, thank you again 🙏

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v2.0.4
