### ISSUE TITLE
Linux - Music Not Working

### ISSUE THREAD

**Issue by git-iso** [bkacjios/m-overlay#16]
After trying mp3s and wavs in Menu and Battlefield in `$USER\.local\share\love\m-overlay\Stage Music (open config didn't work in Manjaro) on m-overlay 1.31, no music played on the CSS or stage. Changing audio backend in Dolphin, removing all spaces in the file path, looping music, and changing volume level did nothing.

**Comment by bkacjios** [comment]
I have yet to test the music player in Linux. I'll guess I'll have to boot into Linux and see what's up. In the meantime, if you run the love file through a terminal you can get some debug information.

**Comment by bkacjios** [comment]
Welp, I just booted up my Arch Linux install and everything seems fine to me. The `Open config directory` button worked as expected, and it loaded and played a song fine.

**Comment by git-iso** [comment]
I set ptrace access and ran the love file in user mode in terminal, and it worked. Running it as root causes xdg-open to not find a valid browser command to open the file.

Dolphin (KDE File Picker, not emulator)
`Executing Dolphin with sudo is not possible due to unfixable security vulnerabilities.
`
Firefox
`Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/iso/.Xauthority which is owned by iso.)
`
Chromium
`[53723:53723:0722/071548.017350:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
`
This makes the file unable to run when selected from a file picker GUI, and forces the p-trace terminal method without sudo.

**Comment by bkacjios** [comment]
Don't run the overlay as root.
