### ISSUE TITLE
Input Display Always Shows an All Black Screen. Settings Always Shows an All White Screen

### ISSUE THREAD

**Issue by christianrei** [bkacjios/m-overlay#163]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/10842996/211177010-6e763e2a-f198-440b-902f-0dba4660d4f8.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/10842996/211177015-97202c4b-1901-4372-bcbf-464433ee42cd.png">

I've just downloaded this for the first time on Windows and I can't seem to get it working. It says it is connected to my dolphin and it switches the ports but it always just shows a black screen. I press escape to try to play with the settings but it just swaps to an all white screen. Searched around the README but don't see anything I can do to fix this. Am I missing something? Thanks.

**Comment by bkacjios** [comment]
You need to update your video card drivers. See issue #152
