### ISSUE TITLE
Application crashes after a while

### ISSUE THREAD

**Issue by cbartsch** [bkacjios/m-overlay#164]
**Describe the bug**
I am using m-overlay during my streams and I realized after a while the input display is just gone.
Today I have only one clip where the input display is showing and all the later clips it's missing. The application just closed itself without any error message.

This is new after updating to version 2.1.0.
And I think it happened on an older version too, some sort of memory leak?

**Desktop (please complete the following information):**
 - OS: Windows
 - Dolphin Version: Slippi 3.0.3

**To Reproduce**
Use m-overlay with Slippi and OBS for 1+ hours.

**Expected behavior**
Application does not crash

**Debug console output**
```
[DEBUG - 01:56:23] Love2D 11.4.0 - Mysterious Mysteries
[DEBUG - 01:56:23] Lua 5.1 (LuaJIT 2.1.0-beta3)
[DEBUG - 01:56:23] M'Overlay (2.1.0)
[INFO  - 01:56:23] [DOLPHIN] Hooked
```
**Additional info**
Sometimes the application stops responding:
![image](https://user-images.githubusercontent.com/3541682/217120969-394dde9f-f70a-4598-8598-ab6662d34eea.png)

**Comment by bkacjios** [comment]
The console log resets as soon as you re-open the program, so it looks like the log you provided was after you relaunched. Can you check if there's any crashlogs available in your config directory?

**Comment by cbartsch** [comment]
Doesn't look liie there's anything: 
![image](https://user-images.githubusercontent.com/3541682/217379223-4eee19ec-83f9-4e79-aab3-9f7b01d795aa.png)

I'll try checking the log next time it crashes, before reopening it.

**Comment by cbartsch** [comment]
OK so I just played some Unranked games with m-overlay open. It didn't crash but then I opened OBS and after a few games it crashed right when starting a game.

Log:
[console.log](https://github.com/bkacjios/m-overlay/files/10680427/console.log)

**Comment by cbartsch** [comment]
Here's some more info from Windows Event Logs, not sure if those help at all:

```
Faulting application name: m-overlay-x64.exe, version: 2.1.0.0, time stamp: 0x61d1af1e
Faulting module name: lua51.dll, version: 0.0.0.0, time stamp: 0x61d1ae70
Exception code: 0xc0000005
Fault offset: 0x000000000004ddfc
Faulting process ID: 0x5c38
Faulting application start time: 0x01d93b41f31663d7
Faulting application path: H:\Dropbox (Personal)\stream\m-overlay\m-overlay-x64.exe
Faulting module path: H:\Dropbox (Personal)\stream\m-overlay\lua51.dll
Report ID: 313743e4-b92b-43ce-8371-e5f2fa2cbc53
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: m-overlay-x64.exe
P2: 2.1.0.0
P3: 61d1af1e
P4: lua51.dll
P5: 0.0.0.0
P6: 61d1ae70
P7: c0000005
P8: 000000000004ddfc
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_m-overlay-x64.ex_2be213534e8ace197b85f5c44f85f4fd1a799d7_1b66d2dd_12acf131-3fd1-4210-a245-393bca3868f0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 313743e4-b92b-43ce-8371-e5f2fa2cbc53
Report Status: 4
Hashed bucket: 
Cab Guid: 0
```

```
Fault bucket 1325386182198994988, type 4
Event Name: APPCRASH
Response: Nicht verfügbar
Cab Id: 0

Problem signature:
P1: m-overlay-x64.exe
P2: 2.1.0.0
P3: 61d1af1e
P4: lua51.dll
P5: 0.0.0.0
P6: 61d1ae70
P7: c0000005
P8: 000000000004ddfc
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER82FA.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_m-overlay-x64.ex_2be213534e8ace197b85f5c44f85f4fd1a799d7_1b66d2dd_12acf131-3fd1-4210-a245-393bca3868f0

Analysis symbol: 
Rechecking for solution: 0
Report Id: 313743e4-b92b-43ce-8371-e5f2fa2cbc53
Report Status: 268435456
Hashed bucket: 81277dfab46c4a9ac264b7b5e42ea82c
Cab Guid: 0
```

```
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>10.0</WindowsNTVersion>
		<Build>19044</Build>
		<Product>(0x79): Windows 10 Education</Product>
		<Edition>Education</Edition>
		<BuildString>19041.2486.amd64fre.vb_release.191206-1406</BuildString>
		<Revision>2486</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1031</LCID>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>m-overlay-x64.exe</Parameter0>
		<Parameter1>2.1.0.0</Parameter1>
		<Parameter2>61d1af1e</Parameter2>
		<Parameter3>lua51.dll</Parameter3>
		<Parameter4>0.0.0.0</Parameter4>
		<Parameter5>61d1ae70</Parameter5>
		<Parameter6>c0000005</Parameter6>
		<Parameter7>000000000004ddfc</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>10.0.19044.2.0.0.256.121</Parameter1>
		<Parameter2>2057</Parameter2>
		<Parameter22>19c6</Parameter22>
		<Parameter23>19c6e72383efef36135b9705bbaa6ac5</Parameter23>
		<Parameter24>231b</Parameter24>
		<Parameter25>231b197cdc44fd07a5c4ab38d9b56cbc</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>D3A1A55A-BFF8-4BDF-9B48-1DBEC8FE5ABA</MID>
		<SystemManufacturer>Micro-Star International Co., Ltd.</SystemManufacturer>
		<SystemProductName>MS-7B79</SystemProductName>
		<BIOSVersion>H.00</BIOSVersion>
		<OSInstallDate>1638819226</OSInstallDate>
		<OSInstallTime>1601-01-02T22:32:23Z</OSInstallTime>
		<TimeZoneBias>-01:00</TimeZoneBias>
	</SystemInformation>
	<SecureBootState>
		<UEFISecureBootEnabled>NotCapable</UEFISecureBootEnabled>
	</SecureBootState>
	<ReportInformation>
		<Guid>12acf131-3fd1-4210-a245-393bca3868f0</Guid>
		<CreationTime>2023-02-07T23:03:10Z</CreationTime>
	</ReportInformation>
</WERReportMetadata>
```

**Comment by cbartsch** [comment]
So today I streamed for 5 hours and it didn't crash. I had the "debug inputs" enabled last time where it shows your stick X/Y coordinates. Maybe it's got to do with that?

Also when closing it after stream, it hung again:
![image](https://user-images.githubusercontent.com/3541682/217676127-6dbe08d9-9844-4188-8f33-b8c59bcae6f5.png)

**Comment by jjvliu** [comment]
I have the same issue with M'Overlay and Melee. My case also started after 2.10 and leaves no crashlogs in the config directory. I do not have debug inputs enabled.

1. Every 5 games or so, the application silently exits. For me it is very obvious because the music stops. This only ever occurs after a game ends, when going back to the character select screen. I mostly play local Versus Mode.

2. After most sessions, the application stops responding after closing Dolphin (Slippi). Here is a Windows event log:

```
Log Name:      Application
Source:        Application Error
Date:          2023-02-11 11:49:10 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Teostra
Description:
Faulting application name: m-overlay-x64.exe, version: 2.1.0.0, time stamp: 0x61d1af1e
Faulting module name: lua51.dll, version: 0.0.0.0, time stamp: 0x61d1ae70
Exception code: 0xc0000005
Fault offset: 0x0000000000042689
Faulting process id: 0x948
Faulting application start time: 0x01d93e505cacac2e
Faulting application path: C:\Users\Jimmy\AppData\Local\Programs\M'Overlay\m-overlay-x64.exe
Faulting module path: C:\Users\Jimmy\AppData\Local\Programs\M'Overlay\lua51.dll
Report Id: c9fe9417-394a-4d52-9786-09ab8018eccc
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-02-11T19:49:10.5664996Z" />
    <EventRecordID>86827</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Teostra</Computer>
    <Security />
  </System>
  <EventData>
    <Data>m-overlay-x64.exe</Data>
    <Data>2.1.0.0</Data>
    <Data>61d1af1e</Data>
    <Data>lua51.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>61d1ae70</Data>
    <Data>c0000005</Data>
    <Data>0000000000042689</Data>
    <Data>948</Data>
    <Data>01d93e505cacac2e</Data>
    <Data>C:\Users\Jimmy\AppData\Local\Programs\M'Overlay\m-overlay-x64.exe</Data>
    <Data>C:\Users\Jimmy\AppData\Local\Programs\M'Overlay\lua51.dll</Data>
    <Data>c9fe9417-394a-4d52-9786-09ab8018eccc</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by cbartsch** [comment]
Update - I had it crash today, looks like it died after about 2 hours of streaming. Video: https://www.twitch.tv/videos/1738607916?t=00h07m09s

It just disappears after that game linked in the timestamp.

**Comment by bkacjios** [comment]
Interesting. That certainly helps. I left dolphin running over ight with the overlay open and didn't get a crash at all, so it must be related to the memory reading.

Since you can replicate it so easily I can make a build which logs every single update of memory the application is receiving and decoding. I'll try to get it uploaded for you sometime tomorrow. There must be an unexpected memory state which is causing things to break.

**Comment by bkacjios** [comment]
But after following along that stack trace, looks like it's following a pointer to another pointer then erroring when trying to decode a JIS string, probably the appointment name.  I don't actually use those values for anything but had been toying around with an idea for displaying ranks a bit ago.

I'm curious if you ran into any players with weird characters in their name.

**Comment by bkacjios** [comment]
[m-overlay-x64-portable.zip](https://github.com/bkacjios/m-overlay/files/10922552/m-overlay-x64-portable.zip)

Mind giving this test build a try? I realized I was using 32bit address spaces for determine the memory region of the gamecube ram. Changed that to handle 64bit as it should. Also disabled the suspect areas of memory I was reading from.

**Comment by bkacjios** [comment]
Alright, cool. Thanks for testing. If it seems all good by tomorrow night I'll push an official update.

**Comment by bkacjios** [comment]
That.. makes no sense. It's erroring decoding a memory type that I completely disabled in that build I provided.

**Comment by bkacjios** [comment]
I'm a dumb ass. I forgot my portable version is just a launcher now that downloads the latest official release from here. I'll need to make a new build for you to try without that..

**Comment by bkacjios** [comment]
[m-overlay-x64-portable.zip](https://github.com/bkacjios/m-overlay/files/10926659/m-overlay-x64-portable.zip)

Try this. You will know it's a debug build if you check the about tab in the escape menu. The version will look weird. There's also a dark mode theme I was working on..

![Image](https://files.bitassemble.com/m-overlay-x64_onQ7R7b2bH.png)

**Comment by bkacjios** [comment]
I almost wonder if it's a bad song causing the crash.. I can't replicate the crash on my end, so I really don't think it's a memory reading issue. I can change the "playing track" message to include the file path of the song. Hopefully this can help pinpoint a possible cause for the crash.

**Comment by bkacjios** [comment]
Damn.. I'm really at a loss. I did just push out an update with the fixes for the errors @voguelike mentioned, so the beta should be obsolete now.

**Comment by cbartsch** [comment]
Thanks, I'll try the update today.

**Comment by c-bartsch** [comment]
So far no crashes with the versionf rom https://github.com/bkacjios/m-overlay/issues/164#issuecomment-1461112812

I do get the #169 though if you close m-overlay after closing Dolphin.

**Comment by jjvliu** [comment]
I still get these crashes sometimes on 2.1.1a while playing. When it happens, it is always when returning to character selection after a game. The application silently exits (no hang) like in the original post above.
