### ISSUE TITLE
No Visual UI Appearing on Dolphin/Slippi Melee Startup

### ISSUE THREAD

**Issue by NNatwin** [bkacjios/m-overlay#165]
When booting up Smash Melee on BOTH the regular Dolphin emulator and Slippi Dolphin emulator, the UI for M'Overlay was not appearing. When I pressed esc, the screen would just transition to white, no menu appearing (not even this happens now).

 - OS: Windows 11
 - Dolphin Version: "Faster Melee" Slippi 3.0.3

**To Reproduce**
1. Open M'Overlay
2. Open Dolphin/Slippi (you could reverse step one and two)
3. Click on Smash Melee/Open it
4. Check M'Overlay.
5. See error

**Expected behavior**
I expected to be able to use M'Overlay to see my inputs, though I mostly wanted to use it for custom music purposes to make online less boring. I did not expect to be faced with a blank screen, no visuals, and no menu.

![m-overlay as is](https://user-images.githubusercontent.com/125234341/218363964-5d0cccfc-5903-4585-92b9-8c43b686a05d.png)

![m-overlay console](https://user-images.githubusercontent.com/125234341/218363973-5b1b79c4-9477-4242-84b5-b8e71b86baa3.png)

I hope these images are accessible, I don't know how GitHub stuff works. Apologies.

Open the settings menu by pressing the escape key on your keyboard.
Click on 'Open config directory' and copy/paste the contents of 'console.log' here.
As stated before, pressing the escape key does not work, but the recent portable build I downloaded opens the console automatically so I hope this helps.

[DEBUG - 22:09:27] Love2D 11.4.0 - Mysterious Mysteries
[DEBUG - 22:09:27] Lua 5.1 (LuaJIT 2.1.0-beta3)
[DEBUG - 22:09:27] M'Overlay (2.1.0)
[INFO  - 22:09:27] [DOLPHIN] Hooked
[DEBUG - 22:09:30] [DOLPHIN] Watching ram: 7FFF0000 [2000000]
[INFO  - 22:09:30] [DOLPHIN] Game: GALE01 revision 2
[INFO  - 22:09:30] [DOLPHIN] Loaded game config: GALE01-2
[INFO  - 22:09:30] [MEMORY] Mapped game memory structure
[DEBUG - 22:09:30] [MEMORY] [0x8046B6A5  = 0x00000000] match.info.playing = false
[DEBUG - 22:09:30] [MEMORY] [0x8046B6AE  = 0x00000000] match.info.finished = false
[DEBUG - 22:09:32] [MEMORY] [0x80479D30  = 0x00000028] scene.major = 40
[DEBUG - 22:09:32] [MEMORY] [0x80479D30  = 0x00000001] scene.major = 1
[DEBUG - 22:09:32] [RANDOM] Obtained seed "0x63E9A9EC" from the system time
[WARN  - 22:09:35] Writing to config.json

```
**Additional context**
Let me know if I need to provide anything else but for now this is literally all I can give. It's just a blank screen on startup, I mash all the buttons and nothing shows up. Kind of frustrating, I've been fiddling with it for so long and there doesn't seem to be anyone else with this problem. Hopefully this can prevent something like this in the future, unless its already been solved.

**Comment by bkacjios** [comment]
Update your video drivers.

**Comment by NNatwin** [comment]
Drivers are updated, still nothing.
