### ISSUE TITLE
Crashes in melee after i open unranked/direct

### ISSUE THREAD

**Issue by Enenralives** [bkacjios/m-overlay#167]
i keep getting this issue when i open up unranked/direct in slippi where it crashes
modules/memory/init.lua:221: bad argument #1 to 'lshift' (number expected, got nil)
stack traceback:
	[C]: in function 'lshift'
	modules/memory/init.lua:221: in function 'read'
	modules/memory/init.lua:333: in function 'update'
	modules/memory/init.lua:439: in function 'update'
	modules/memory/init.lua:439: in function 'update'
	modules/memory/init.lua:630: in function 'updatememory'
	modules/memory/init.lua:598: in function 'update'
	main.lua:219: in function 'update'
	[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
	[C]: in function 'xpcall'
	[love "boot.lua"]:370: in function <[love "boot.lua"]:337>
only seems to be the case with a modded iso tho could you tell me how to fix since redownloading is not working?

**Comment by bkacjios** [comment]
The modded ISO must be changing code or address spaces of the game to something the program isn't expecting. Not sure what to tell you other than you should use a stock ISO.

**Comment by Enenralives** [comment]
Yeah it was the character select screen that was having issues I realized sorry for your troubles
