### ISSUE TITLE
Cant open the overlay 

### ISSUE THREAD

**Issue by KingOfStableness** [bkacjios/m-overlay#168]
![image](https://user-images.githubusercontent.com/117735263/222904296-33cf5c9a-51cf-4943-ac62-5885101dfe2d.png)
run using the linux version, appimage love version, and yes, it just cuts off at there

**Comment by bkacjios** [comment]
Oh, this is because of my recent addition to adding an updater.. Hmm.. You may need to install the package `lua51-sec`.

I may have to make a build without the auto-update feature built in to get around this issue on Linux.

**Comment by Njinx** [comment]
@bkacjios This fixed it for me. I'm going to add it to the wiki.
