### ISSUE TITLE
Support for Mario Kart Wii?

### ISSUE THREAD

**Issue by coshinsky** [bkacjios/m-overlay#17]
Are there any plans to support this game?

**Comment by bkacjios** [comment]
I looked into this and I couldn't find the usual memory structure for where gamecube controller inputs are stored. I managed to find something, but the values were completely different that what I was used to and would require a fair bit of work.

**Comment by little512** [comment]
I successfully got Mario Kart Wii working with M'Overlay.

**Comment by little512** [comment]
With the most recent merge, the ports are a bit strange.  So long as you only use port 1 and don't unplug it should work fine.
