### ISSUE TITLE
[Suggestion] "All Series" music folder

### ISSUE THREAD

**Issue by thekirbykid20067** [bkacjios/m-overlay#171]
Suggestion: Have a folder in which songs can be placed that can be played on _any_ stage, regardless of series. This could be useful for players who want a large music library for the game as a whole

**Comment by bkacjios** [comment]
It's not really listed anywhere, but you can put music in the `Series Music` folder and they will be loaded for any series.
This can also be done for the `Stage Music` folder.

https://github.com/bkacjios/m-overlay/blob/d8c629d3d6bf07a1ba7a9bb70b26db7262c3f8bd/source/music.lua#L687
https://github.com/bkacjios/m-overlay/blob/d8c629d3d6bf07a1ba7a9bb70b26db7262c3f8bd/source/music.lua#L682
