### ISSUE TITLE
Source Files and Love2D

### ISSUE THREAD

**Issue by gdiazbanuelos** [bkacjios/m-overlay#176]
When downloading the source files and installing the Love2D game engine, then launching run64, I get this image.

![image](https://github.com/bkacjios/m-overlay/assets/39248490/60ef2ab8-7bf6-4b4d-aabe-0500851c725d)

In the console I get this error:

```
[ERROR - 09:54:29] Thread error (Thread: 0x027f06f4e730)

modules/ssl.lua:8: module 'ssl.core' not found:
        no field package.preload['ssl.core']
        no 'ssl/core' in LOVE game directories.
        no file 'ssl/core' in LOVE paths.
        no file '.\ssl\core.lua'
        no file 'C:\Program Files\LOVE\lua\ssl\core.lua'
        no file 'C:\Program Files\LOVE\lua\ssl\core\init.lua'
        no file '.\ssl\core.dll'
        no file 'C:\Program Files\LOVE\ssl\core.dll'
        no file 'C:\Program Files\LOVE\loadall.dll'
        no file '.\ssl.dll'
        no file 'C:\Program Files\LOVE\ssl.dll'
        no file 'C:\Program Files\LOVE\loadall.dll'
stack traceback:
        [C]: in function 'require'
        modules/ssl.lua:8: in main chunk
        [C]: in function 'require'
        modules/https.lua:10: in main chunk
        [C]: in function 'require'
        modules/web/thread.lua:1: in main chunk
stack traceback:
        [C]: in function 'error'
        [love "callbacks.lua"]:181: in function <[love "callbacks.lua"]:180>
        main.lua:786: in function <main.lua:774>
        [C]: in function 'xpcall'
        [love "boot.lua"]:370: in function <[love "boot.lua"]:337>
```

I would like to make some changes but I can't get it to run in Love2D. Any help troubleshooting this would be appreciated! Thank you!

**Comment by gdiazbanuelos** [comment]
It seems that the auto-updater update broke the Love2D run64 shortcut. When I download version 2.0.4a and older, it all works correctly when launching run64

**Comment by bkacjios** [comment]
You can copy the ssl.dll from the portable install download to wherever love2d is installed. It's the Lua module lua-sec, that I had to compile and include myself, for the auto updater to work. Love2D 11 doesn't support HTTPS by default, which kinda sucks.

**Comment by gdiazbanuelos** [comment]
Thank you that fixed the issue!
