### ISSUE TITLE
Slippi Dolphin Mainline-Beta support

### ISSUE THREAD

**Issue by abandon-the-flesh** [bkacjios/m-overlay#187]
**Describe the bug**
M'Overlay doesn't detect any open Dolphin instances and does not load when the Slippi Mainline Version is launched.

**Desktop (please complete the following information):**
 - OS: Latest Windows 10
 - Dolphin Version: Slippi 2.11.0 Launcher Version.  Mainline Slippi Dolphin 4.0.0-mainline-beta.1
 ( please see https://github.com/project-slippi/dolphin )

**To Reproduce**
Open Dolphin
Launch compatible game
"Waiting for Dolphin" displays on M'Overlay

**Expected behavior**
M'Overlay to detect Dolphin version and game.

**Screenshots**
![image](https://github.com/bkacjios/m-overlay/assets/113798989/2e3b0fc8-6530-4e82-a48d-533d4fe8bb99)
![image](https://github.com/bkacjios/m-overlay/assets/113798989/1c14d4d6-8231-4a03-9f56-42d9f3d41330)

**Debug console output**
N/A

**Additional context**
N/A

**Comment by bkacjios** [comment]
What's the exe file name? Should be easy to add support for this.

**Comment by abandon-the-flesh** [comment]
Slippi Launcher/netplay-beta/Slippi_Dolphin.exe
Looks like it just adds an underscore.

**Comment by bkacjios** [comment]
Sigh. Yeah, that'll do it. If you remove the underscore m'overlay will work. Pushing out a fix now though.

**Comment by bkacjios** [comment]
Fix out.

**Comment by abandon-the-flesh** [comment]
Ah I see what you mean. Noted for the future. Thanks.
