### ISSUE TITLE
Game Support Request Mario Golf: Toadstool Tour NTSC-J

### ISSUE THREAD

**Issue by spyfox26** [bkacjios/m-overlay#190]
Would be awesome if Mario Golf Toadstool Tour NTSC-J could be added to the games list, as it is the more optimal version of the game for speed running and has several other QoL changes compared to the NTSC-U version. Thank you for the consideration!

**Comment by MORImementos** [comment]
I've submitted a PR for it - should be more or less identical to the structure of the US version

**Comment by bkacjios** [comment]
Added in 93c6a070191436ff4a9e44774c832f8b9e7e1dc9
