### ISSUE TITLE
Game capture in OBS is not picking it up

### ISSUE THREAD

**Issue by Roulff** [bkacjios/m-overlay#2]
I used game capture to specific window but it is not going through, unfortunately.
Window capture works but not transparency.

**Comment by bkacjios** [comment]
I'm guessing you figured this out since you closed it?

If not, it's working fine for me.

https://i.imgur.com/1IBHnrE.png

**Comment by Roulff** [comment]
Yeah, apparently running obs with admin kinda fixes it. Something like
that. You might wanna add that as a recommendation tho. Thanks for making
this cool overlay.
Also, anyway to make it work for P+, or at least some guidance on what I'd
have to work on to make it work on P+?

Thank you so much!

**Comment by bkacjios** [comment]
I could look into getting it to work in project+, shouldn't be too difficult. Mostly just have to find the spots in memory where the controller data is stored.

**Comment by Roulff** [comment]
Let me know if there's anything I can do to help. You can add me on discord at Fluor#4753

**Comment by bkacjios** [comment]
Good news, was pretty easy to get working in P+

https://i.imgur.com/BE61m7j.jpg

I guess I just need to add game detection so it can work in both melee/brawl/P+

**Comment by Roulff** [comment]
PogU! Are you gonna update the code tonight? Thank you!!!

**Comment by bkacjios** [comment]
I'm going to try to get a new release out sometime tonight. I have game detection working for the most part right now. Just need to do a few more things to get it to work right.

The only version that has a combined L/R is for the Slippi version. If you aren't using Slippi to mirror melee from an actual game console, use this release instead. https://github.com/bkacjios/m-overlay/releases/tag/0.5 The way slippi mirrors the game from an actual wii loses the separate L/R data and combines them into a single analog bar.

**Comment by Roulff** [comment]
Oh, yeah that's the version I've been using.
The taunt is just to guarantee the stream can see when someone taunts lol xD
I think I can edit the DPAD images to make that if it is too much work for you. But hopefully, I'll be able to test with P+ tonight, and use it on stream tomorrow =)
You are more than welcome to join us if you are from the East Coast, https://challonge.com/events/fws3/

Thanks again =)

**Comment by bkacjios** [comment]
Welp, it's released.

https://github.com/bkacjios/m-overlay/releases/tag/v0.5

Let me know if you have any issues.
