### ISSUE TITLE
Player codes not being passed to memory.slippi

### ISSUE THREAD

**Issue by noahpodgurski** [bkacjios/m-overlay#202]
https://github.com/bkacjios/m-overlay/blob/6dbc28926d567da550c469316582c35bb34fd52c/source/modules/games/GALE01-2.lua#L162

Even when uncommented I'm not seeing the code appear under `memory.slippi.players.1.code`

**Comment by bkacjios** [comment]
I don't use that for anything in the overlay. It used to work, since I was thinking about adding player ranks to the overlay.

Not sure what to tell you.

**Comment by noahpodgurski** [comment]
Well it worked back when I submitted my [MR](https://github.com/bkacjios/m-overlay/pull/159) but slippi must've been updated to change where it's stored in the data or something...

**Comment by bkacjios** [comment]
Yeah, the data is 100% there, just not being parsed correctly I guess.

![image](https://github.com/bkacjios/m-overlay/assets/3247233/4158f97f-3cdf-4a28-9062-e67d1322f27b)

**Comment by bkacjios** [comment]
Changing this line from

```lua
return convertJisStr(value:match("(.-)%z*") or value) 
```

to

```lua
return convertJisStr(value:match("(.-)%z+") or value) 
```

Somehow allows it to work right. Doesn't really make sense, but I guess that should help you.

**Comment by noahpodgurski** [comment]
Thank you

**Comment by bkacjios** [comment]
Actually.. I think this is a better pattern.

`^(.-)%z-$`

The anchors are what allows it to work correctly.

**Comment by bkacjios** [comment]
![image](https://github.com/bkacjios/m-overlay/assets/3247233/d698b001-8dd0-4bb3-8355-bc08760c340d)
And confirmed it works.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/commit/c14d293d8a4f0842aa19bceae0fd1df325020d80
