### ISSUE TITLE
FLAC and OPUS support for music player?

### ISSUE THREAD

**Issue by Carldacious** [bkacjios/m-overlay#21]
I wanted to see if it were possible to add support for FLAC and OPUS for the Melee music player!

Amazing work on this project! Really love what you are doing!

**Comment by bkacjios** [comment]
I think flac files should work, actually. [According to this it should.](https://love2d.org/wiki/Audio_Formats)

**Comment by Carldacious** [comment]
Awesome! You're right! They do! Thanks a bunch! 

I'm guessing if LOVE adds OPUS that will be supported as well. Here's hoping!

Thanks again!

**Comment by Carldacious** [comment]
I made a mistake before. FLAC files are not working, sadly.

If you load a file type that works (WAV/MP3/OGG) originally when loading the app, it will continue to be able to play it, that's why I was confused.

Anyway to resolve this since LOVE supports FLAC?

**Comment by bkacjios** [comment]
Oh whoops. Yeah, I currently filter out audio files by their file extension. I should add flac to that list I guess!

**Comment by Carldacious** [comment]
Awesome!! Thanks so much!

**Comment by bkacjios** [comment]
Flac should now be supported in 1.4.0
