### ISSUE TITLE
Won't work for any games other then melee

### ISSUE THREAD

**Issue by Waddle6212** [bkacjios/m-overlay#210]
I open the application, open dolphin, and open any game other than melee, and i get this error

modules/games/core.lua:92: attempt to perform arithmetic on local 'r' (a nil value)
stack traceback:
	modules/games/core.lua:92: in function 'translateTriggers'
	overlay/skins/S-Stick.lua:188: in function 'drawButtons'
	overlay/skins/S-Stick.lua:262: in function <overlay/skins/S-Stick.lua:200>
	overlay/init.lua:52: in function 'call'
	overlay/init.lua:44: in function 'draw'
	main.lua:379: in function 'drawControllerOverlay'
	main.lua:679: in function 'draw'
	[love "callbacks.lua"]:168: in function <[love "callbacks.lua"]:144>
	[C]: in function 'xpcall'
	[love "boot.lua"]:377: in function <[love "boot.lua"]:344>

**Comment by Waddle6212** [comment]
Nvm I found it, open the installer and un-check "Create Desktop Shortcut"

**Comment by bkacjios** [comment]
Looks like you were tying to use the S-Stick skin, which I guess is currently broken.
