### ISSUE TITLE
map dpad different buttons.

### ISSUE THREAD

**Issue by MoltenxCrystal** [bkacjios/m-overlay#22]
It should be possible to change the buttons for switching music because dpad down is used for extended samus grapple.

**Comment by bkacjios** [comment]
Ah, good point. I forgot about samus' extended grapple. I'll try adding an option in the settings menu to allow you to change the button to whatever you want.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.3.4

This should fix this issue.
