### ISSUE TITLE
Having Trouble Getting M'Overlay to support Brawl/P+

### ISSUE THREAD

**Issue by esong501** [bkacjios/m-overlay#23]
Each time I start Brawl or P+, M'Overlay says that RSBE01-2 is unsupported. I went into the iso details on Dolphin and my Brawl iso is revision 2, is this an unsupported version of Brawl?

**Comment by bkacjios** [comment]
Oh, huh, interesting. I didn't realize their was a reversion 2 of brawl. I guess my disk is a bit older. But yeah, for now I guess that version is unsupported. I'll have to figure out the memory addresses for that version specifically.

**Comment by bkacjios** [comment]
I looked into this, and I found that there between version 1 and 2 they didn't change the location where the inputs are stored. Marked this revision as a clone, so it will now load into brawl mode properly.

https://github.com/bkacjios/m-overlay/releases/tag/v1.3.5
