### ISSUE TITLE
[REQUEST] Always have option to select which port

### ISSUE THREAD

**Issue by ddulude95** [bkacjios/m-overlay#24]
It would be cool to always be able to select which port that instance of moverlay is displaying. This would be useful because if you're playing offline with a buddy of yours and want two overlays up, you could just open moverlay twice and select each port.

Also, I noticed even with "auto detect port" in slippi unranked, it still will sometimes select their port and checking-unchecking the auto detect button doesnt change anything.

Really awesome program though! Thanks for developing this!

**Comment by bkacjios** [comment]
I actually sort of have a setting for this! Make a new shortcut of the exe and add `--port=2` or whatever port you want to be default to the target path.

![Default port](https://i.imgur.com/VozokuL.png)

**Comment by ddulude95** [comment]
Is it possible to just have a drop down list of ports to select? Because then you can update it dynamically if it happens to break in between matches. I dont know how it broke in between matches

**Comment by ddulude95** [comment]
Oh I just noticed on the front page it says you can switch which port is displaying by using scroll wheel or keyboard...im dumb lol. I guess I could try to find out why it breaks

**Comment by bkacjios** [comment]
The debug console may have some useful information for this too. It will say things like `[AUTOPORT] Slippi local player index changed, changing to port X` or `[AUTOPORT] Forcing port X in menus` and `[AUTOPORT] Switching to slippi local player index X`

**Comment by bkacjios** [comment]
Closing this since you haven't got back to me. If you experience this issue still or have more info, please feel free to reopen.
