### ISSUE TITLE
Melee Music Suggestion

### ISSUE THREAD

**Issue by buvk** [bkacjios/m-overlay#26]
I was wondering if it would be possible to also support stage music by series (similar to how it is setup in Ultimate).  What I mean by this is you could have an F-Zero folder, and the music in that folder would apply to both Big Blue and Mute City.  This would eliminate having duplicate songs assuming one were to set it up this way.

Maybe it could be mapped like this?

Stage | Series | Count of Series
-- | -- | --
Battlefield | Super Smash Bros | 3
Big Blue | F-Zero | 2
Brinstar | Metroid | 2
Brinstar Depths | Metroid | 2
Corneria | Star Fox | 2
Dream Land N64 | Kirby | 3
Final Destination | Super Smash Bros | 3
Flat Zone | Game & Watch | 1
Fountain of Dreams | Kirby | 3
Fourside | Earthbound | 2
Great Bay | The Legend of Zelda | 2
Green Greens | Kirby | 3
Hyrule Temple | The Legend of Zelda | 2
Icicle Mountain | Ice Climbers | 1
Jungle Japes | Donkey Kong | 3
Kongo Jungle | Donkey Kong | 3
Kongo Jungle N64 | Donkey Kong | 3
Menu | Super Smash Bros | 3
Mushroom Kingdom | Super Mario | 4
Mushroom Kingdom 2 | Super Mario | 4
Mute City | F-Zero | 2
Onett | Earthbound | 2
Poké Floats | Pokemon | 2
Pokémon Stadium | Pokemon | 2
Princess Peach's Castle | Super Mario | 4
Rainbow Cruise | Super Mario | 4
Venom | Star Fox | 2
Yoshi's Island | Yoshi | 3
Yoshi's Island N64 | Yoshi | 3
Yoshi's Story | Yoshi | 3

**Comment by bkacjios** [comment]
I was actually thinking about doing something like this. I'll add it to my to-do list.

**Comment by bkacjios** [comment]
I also had an idea where if all the character are from the same series are in a match, it could mix in their series music as well alongside the stage music.

**Comment by bkacjios** [comment]
Added this feature in 1.4.0
