### ISSUE TITLE
Question on how to build on Windows?

### ISSUE THREAD

**Issue by gdiazbanuelos** [bkacjios/m-overlay#27]
Hello!

This may be a dumb question but I would like to tinker around with this program's source code but how do I build it on Windows? I downloaded the source files but how do I compile it to run my own version?

Thank you so much for your help and time!

**Comment by bkacjios** [comment]
Install [love2d 11.3](https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.exe)

Just doing that alone will allow you to run the `run64` shortcut which will run the source code.

If you want to actually build it into a release package, download and install [7Zip](https://www.7-zip.org/download.html) and add it to your windows environment PATH.

![PATH Entry](https://i.imgur.com/xU0xfS6.png)

Download and place [rcedit-x64](https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe) in the main source folder (in the same folder where release.bat and run64 are)

You should then have the bare minimum to run the `release.bat` to create the .love file and zip of the packed exe.

If you want to create the installation exe, you need [Inno Setup](https://jrsoftware.org/isdl.php)

**Comment by gdiazbanuelos** [comment]
Thank you so much for the response! I got it working on my computer now. Thanks!
