### ISSUE TITLE
Music Looping on the Menu

### ISSUE THREAD

**Issue by Carldacious** [bkacjios/m-overlay#29]
If I want tracks to loop on the Menu, sometimes I have to disable and re-enable 'Loop stage song' when I return to the menu to force the looping to occur on the menu.

On some occasions it works perfectly, though many times it goes to the next track. Stages seem to consistently loop though! It's only the Menu where I notice this issue.

**Comment by bkacjios** [comment]
The `Loop stage song` is currently programmed to only loop the song while in a stage. That makes sense though, because I have it so if you check the option when a song is playing it will mark the file as a loop, but when you load out of that menu and back, that marker will be reset.

**Comment by Carldacious** [comment]
Ah, that makes sense. So this is the intended behavior.

Is there any way to make this feature toggle-able for the menu? I have created loops for the stages and the menu and it would be cool to have them both work so that my loops...well, loop!

Thanks so much for your work and quick responses! This is seriously so cool! I can't stop playing with it!

**Comment by bkacjios** [comment]
I guess I could just make the toggle work on everything. Sometimes when I'm working on this project though I leave it open while in the menu, so I was sort of getting bored of hearing the menu music repeat all the time. Lol.

**Comment by Carldacious** [comment]
I totally get it! It makes sense to have it set up like that if you're using it like a music player.

Maybe it's more trouble to add the toggle, but I do like the idea of having the option for the Menu to work differently, in the case like you're saying where you leave it idle for a longer period having it not loop could be good. 

I do agree that for typical use though, looping is the way to go.

**Comment by bkacjios** [comment]
In the next update "Loop stage song" checkbox will be changed into a multi-option box instead.

![New music mode setting](https://i.imgur.com/dLrlDKH.png)

This will allow you to select 4 different music modes.

1. Playlist mode
    * Will play the next song in the list when a song ends.
2. Loop menu
    * Will loop the current song being played continuously in the menus.
3. Loop stage
    * Will loop the current song being played on the current played stage.
4. Loop all
    * Will loop the current song being played in the menus or while playing on a stage.
