### ISSUE TITLE
Custom Music Slight Delay

### ISSUE THREAD

**Issue by SupahBeebz** [bkacjios/m-overlay#30]
Huge fan of this btw. Just a minor critique that I wanted to issue (if it’s even doable). With Custom Music enabled, playback initiates around 1-2 seconds after the match starts. If it’s possible, could you make it start immediately when the stage pops up -before the announcer says “Ready”- to get more of an authentic/integrated feel to it all. It’s a very minor suggestion, Idk how loading playback works in this software, requesting for immediate feedback could be tedious. Anyways thanks again for making this! Absolutely love it.

**Comment by bkacjios** [comment]
This was an unintentional side effect when making the music end right when the announcer says "GAME!" This should be fixed in the next build. I just need to do some final testing to make sure everything is stable before I release.

**Comment by bkacjios** [comment]
This should be fixed in 1.4.0

**Comment by SupahBeebz** [comment]
Wow! Good stuff man, can't wait!
