### ISSUE TITLE
Regarding Music and Pausing The Game

### ISSUE THREAD

**Issue by SupahBeebz** [bkacjios/m-overlay#31]
Hey, I'm back again lol (sorry). I didn't think of this earlier, I guess since we're on the road to authenticity, is there any way you can reduce the volume of the custom music playing whenever the game is paused? After playing the original game, right when I hit the pause button, the music is reduced by 50-75% of the original volume and then reverts back when I unpause/hit the pause button again. Thanks again man, your response/execution time is very swift.

**Comment by bkacjios** [comment]
It's a possibility. I'll have to find a reliable value in memory to determine if the game is paused.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.4.1

There you go.

**Comment by SupahBeebz** [comment]
Nicely done!! Precisely how it is to the original! With that said, I have one last critique (hopefully lol) - which really isn't worth posting as an issue - I've noticed the menu music starts immediately when I fire up melee. If you can, it should start when the announcer says "MELEE!", also the menu music keeps playing in m-overlay when I shut down Slippi. But that's about it man, I can't think of any other music related stuff.

**Comment by bkacjios** [comment]
I'm not going to do that, sorry. Seems rather pointless. Also, music stops perfectly fine for me when closing slippi and keeping the program open.

**Comment by SupahBeebz** [comment]
fair enough lol, I wonder why my keeps playing then, I have 3 songs on my menu folder btw. I remember it stopping when I had just one song.

**Comment by bkacjios** [comment]
I have 12 songs on my menu, and closing the game or dolphin entirely stops the music. It should also make the overlay say "WAITING FOR GAME..." when it kills the music too.

**Comment by SupahBeebz** [comment]
hmm interesting, not sure what it could be then. it does say "waiting for dolphin..." on the window message, but the overlay still shows. I guess it's on my end then, I'll see what it could've been.

**Comment by bkacjios** [comment]
That's weird. When you have dolphin open but with no game loaded it should say "WAITING FOR GAME..."

The window should be completely blank when dolphin is fully closed. Are you on Linux by any chance?

**Comment by SupahBeebz** [comment]
I'm on Windows 10

**Comment by SupahBeebz** [comment]
If I have time I can send a vid what it looks like if you want...

**Comment by bkacjios** [comment]
Sure.
