### ISSUE TITLE
Controller not being detected and music not playing

### ISSUE THREAD

**Issue by ci0cc0lat0** [bkacjios/m-overlay#33]
![image](https://user-images.githubusercontent.com/14319832/89699805-19366500-d8ef-11ea-9a46-eadf26c0e122.png)
![image](https://user-images.githubusercontent.com/14319832/89699875-d88b1b80-d8ef-11ea-9e5b-aba721487692.png)

So I have an official gamecube controller plugged into a mayflash adapter into slippi dolphin. As seen in the image, M'overlay always thinks I am captain falcon even before I launch melee or after closing it. This also continues despite cycling through ports manually.  I have done several re-installs and all of them on any version always comes back to the same issues. Specifically in melee, my controller inputs are not shown through M'overlay, despite the controller working perfectly fine in game. 

To add to this, music on stages won't play at all. 

If M'overlay is launched first and then just dolphin ( no game ) the program will read that dolphin is the game being read as seen in the last image.
![image](https://user-images.githubusercontent.com/14319832/89699926-33247780-d8f0-11ea-83b5-cc7d88dfe2de.png)
![image](https://user-images.githubusercontent.com/14319832/89699932-446d8400-d8f0-11ea-8686-8aa3b899c299.png)

Thank you for your time.

**Comment by bkacjios** [comment]
Please try this. Close dolphin, open M'Overlay, enable `Debug console` in the settings menu. Launch dolphin and open melee. The console should have a bunch of text you can copy/paste here for me to look at.

**Comment by ci0cc0lat0** [comment]
Thank you for the quick reply. 
This is what I get from the debug console

[INFO  - 22:26:13] [DOLPHIN] Hooked
[INFO  - 22:26:13] [DOLPHIN] Watching ram: AD60000
[DEBUG - 22:26:13] [DOLPHIN] GAMEID: "GALE01" (Version 2)
[INFO  - 22:26:13] [DOLPHIN] Loaded game config: GALE01-2
[INFO  - 22:26:13] [MEMORY] Mapping game memory..
[DEBUG - 22:26:13] [MEMORY] [0][8046B6AE = 00000000] match.finished = false
[DEBUG - 22:26:13] [MEMORY] [0][80479D30 = 00000000] menu_major = 0
[DEBUG - 22:26:13] [MEMORY] [0][80479D33 = 00000000] menu_minor = 0
[DEBUG - 22:26:13] [MEMORY] [0][8046B6A5 = 00000000] match.playing = false
[DEBUG - 22:26:13] [AUTOPORT] Forcing port 0 in menus
[DEBUG - 22:26:13] [MUSIC] Loaded 1 songs in "Melee/Menu Music"
[INFO  - 22:26:13] [MUSIC] Playing track #1 for menu

Also the menu music ( that is places in the menu music folder) plays as soon as dolphin opens.

**Comment by bkacjios** [comment]
Do you have any overlays enabled, such as Discord or nvidia shadow play? I think the program is hooking into something third party rather than the game memory section of dolphin.

Either way, mind trying this version for me?

[m-overlay-x64 (master-128).zip](https://github.com/bkacjios/m-overlay/files/5045907/m-overlay-x64.master-128.zip)

**Comment by ci0cc0lat0** [comment]
I do have a recording software that it is hooking onto. When I ended  the program , I can hear music on the correct stages and see the inputs of my controller. This was before trying the master zip.
When I tried the master zip, and had the program running, the same issues popped up. All in all, it is the my recording program's fault. 

I do not need the recording program running when playing smash/dolphin, it is just something that happens to be always running.  I will kill the recording program before running M'overlay.

If you are curious about the program I have RePlaysTV. 
I got it from here following the instructions. 
https://github.com/lulzsun/RePlaysTV

If you need me to do anything else on my side, let me know. Thanks for the help so far.

**Comment by bkacjios** [comment]
Hmm, weird. The zip I linked is a lot more strict with finding the memory space for the gamecube ram, so I was hoping that would help. That program must be doing something very weird. I'll download it and take a look.

**Comment by ci0cc0lat0** [comment]
The recording program is very "ragtag" and the install process is a little awkward. 
These are the instructions I followed if you are having trouble or their github isn't detailed enough. 
https://www.youtube.com/watch?v=GyWTfz2uYTM

Good luck debugging if continue.
