### ISSUE TITLE
Music not playing with Exclusive WASAPI settings

### ISSUE THREAD

**Issue by Noah670** [bkacjios/m-overlay#34]
When any of the Exclusive WASAPI settings are selected no music is played in m-overlay, it works when switching it back to the Cubeb Audio backend but I have had no luck getting any music with WASAPI. 
![2020-08-08_16-46-38](https://user-images.githubusercontent.com/19517519/89704469-4fc7ba80-d997-11ea-9f17-eaa17b7ff31c.png)

**Comment by bkacjios** [comment]
M'Overlay doesn't support WASAPI and I have no way of supporting it right now.
