### ISSUE TITLE
Super Mario Sunshine (GMSP01/ GMSJ01) not recognized!

### ISSUE THREAD

**Issue by Freakzzar** [bkacjios/m-overlay#37]
Hello. First of all thank you for this nice work. I like the input overlay :D 
But sadly only the NTSC-U version of Super Mario Sunshine gets recognized.
I would really appreciate if you could add the Japan version (GMSJ01) and the PAL version (GMSP01)

Thanks!

P.s keep up the good work

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.4.3
