### ISSUE TITLE
M'Overlay not detecting Slippi

### ISSUE THREAD

**Issue by DDS-D** [bkacjios/m-overlay#38]
Hello, 

M'Overlay doesn't seem to detect slippi. The display never shows while Slippi / Melee is running. It just shows waiting for Dolphin. 
![overlay-slippi](https://user-images.githubusercontent.com/69645386/90167063-2d53e980-dd69-11ea-881d-76d0133f5e53.PNG)

When I run Dolphin 5.0, M'overlay connects like normal. 
![Dolphin-overlay](https://user-images.githubusercontent.com/69645386/90167075-30e77080-dd69-11ea-9a21-09f71113bfba.PNG)

Is there any work around for this issue? 

Thanks :)

**Comment by bkacjios** [comment]
Make sure slippi's exe hasn't been renamed to anything. It needs to be named `Dolphin.exe`

You can also enable a debug console by pressing escape for more information, but seeing how it's not even finding the program, I can only assume it's not finding the correct executable.

**Comment by DDS-D** [comment]
It was exactly that. Thanks for the quick reply.
