### ISSUE TITLE
Mac OSX via Love?

### ISSUE THREAD

**Issue by kansha93** [bkacjios/m-overlay#39]
**Describe the bug**
Blue screen when loading .love file on Love app (see below)
![image](https://user-images.githubusercontent.com/6431730/90189037-56787800-dd71-11ea-9520-6b9bd1a1884c.png)

**Desktop (please complete the following information):**
 - OS: MacOSX 10.15.3
 - Dolphin Version:  Slippi 2.2.1

**Comment by bkacjios** [comment]
OSX doesn't have support at the moment. I have a memory watching module that is partially implemented in C, which can be found [here](https://github.com/bkacjios/m-overlay/tree/master/source/modules/memory). I don't have an OSX core, so it won't work. I would like to support OSX, but I don't have a Mac and VM's are awful to work with when it comes to apple stuff.

**Comment by bkacjios** [comment]
I have done a bit of research into some of the C calls that would be needed to get this to work if someone would like to implement this themselves.

`proc_listpids` to get all the current running processes.
`proc_pidinfo` to get the name of the process and check if it's dolphin.
`task_for_pid` to get the task
`vm_read` to read the tasks memory.

**Comment by bkacjios** [comment]
Closing because of discussion in #97
