### ISSUE TITLE
B0XX Support

### ISSUE THREAD

**Issue by IvantheTricourne** [bkacjios/m-overlay#4]
I've seen this overlay on several streams, and I gotta say, it's quite good! Really nice work.

I'm just curious what it would take to support a [B0XX](https://b0xx.com/) layout. As I'm a B0XX user, it would be very useful for me to have this. This is quite different from the existing B0XX input viewer (which is available [here](https://b0xx.com/pages/resources)), mainly due to the fact that this uses a transparent background.

Let me know what you think! I'd be happy to look into this myself, but I'm just not quite sure how to go about building this on my machine.

**Comment by bkacjios** [comment]
I'm not sure. The way the overlay currently works is by reading the games memory where input values are stored. Since the boxx has buttons for analog, I'm not entirely sure how I would go about handling that.

After looking into it though, it seems the boxx is actually a DInput device when hooked up to a PC, so I think it could be possible to make an overlay for it. It would be outside the scope of this project though and I would make a separate program just for the boxx.

**Comment by IvantheTricourne** [comment]
> I'm not sure. The way the overlay currently works is by reading the games memory where input values are stored. Since the boxx has buttons for analog, I'm not entirely sure how I would go about handling that.
> 
> After looking into it though, it seems the boxx is actually a DInput device when hooked up to a PC, so I think it could be possible to make an overlay for it. It would be outside the scope of this project though and I would make a separate program just for the boxx.

I tried it myself using a Wii U adapter and everything seemed to work just fine. If anything, I was more or less suggesting a simple overlay for the B0XX. However, as you mentioned, the B0XX does support DInput, which is how I usually use it on Dolphin (i.e., a direct connect to the PC). It would be interesting to hear more about what you think a separate program would be.

**Comment by bkacjios** [comment]
I see. Well, what I was thinking was I would make a separate program and use DInput to handle reading the button presses and what not. Would make things a lot easier and would also work without even needing dolphin running. Basically, I'd be making a new version of their B0XX input viewer lol

It would honestly be really really easy. The only thing I would need is a list of all the buttons and what numbers they are registered as in the DInput device.

![Image of DInput reading](https://i.imgur.com/s9HQ1DG.png)

Like I already made a little test program and got it reading DInput values from my 8bitdo controller rather easily. It just all comes down to making the actual overlay and such.

**Comment by IvantheTricourne** [comment]
@bkacjios I can get those for you. How exactly should I get them? Sorry I'm not really familiar with how that stuff works.

**Comment by IvantheTricourne** [comment]
Idk why my comment is being updated, but [here is the link to some overlay images](https://drive.google.com/open?id=1_1I_gbYRHn2RWYxFTaQn8PiXhXiAR7E6).

**Comment by bkacjios** [comment]
Mind taking a screenshot of your controller settings in dolphin for me too? That should give me everything I need to make this.

**Comment by IvantheTricourne** [comment]
@bkacjios Controller settings? Not sure exactly what you mean. But, In the recent FM build (i.e., Slippi), there's a file for B0XX. What I basically do is use the `Standard Controller` option, then load the B0XX profile.

![image](https://user-images.githubusercontent.com/8952096/82699098-fffc1180-9c39-11ea-8591-43561083b93e.png)

![image](https://user-images.githubusercontent.com/8952096/82699077-f5da1300-9c39-11ea-9e86-9d01fad73b8b.png)

**Comment by bkacjios** [comment]
The second image is what I wanted, but preferably with the BOXX profile loaded.

**Comment by IvantheTricourne** [comment]
I updated the image with the profile loaded for the B0XX

**Comment by bkacjios** [comment]
Okay sweet. Well, I'll see if I can try to get something working. My only concern is how to manage the sticks since the buttons are apparently setting an analog value in one of the axis. I'm not sure if I will be able to properly display the MODX and MODY buttons.

**Comment by IvantheTricourne** [comment]
Hmm, do you have access to the coordinate values of the stick? The Mod buttons + direction correspond to a certain coordinate value. Otherwise, I think it would still be useful nonetheless to have!

**Comment by bkacjios** [comment]
Yeah, I do have access to those values. I was planning on doing something like detecting how far the analog value is going. If it's less than 50% tilt, I'd assume it was pressed with a modifier.

**Comment by IvantheTricourne** [comment]
You can (faintly) see the white dots in these images. These correspond to the analog stick values when pressed with one or more of the 4 cardinal directions.

Mod X coordinates:

![image](https://user-images.githubusercontent.com/8952096/82700320-fa073000-9c3b-11ea-8d0d-7884ec971fc8.png)

Mod Y Coordinates:

![image](https://user-images.githubusercontent.com/8952096/82700365-0ee3c380-9c3c-11ea-8047-5e89b58f5ae4.png)

**Comment by bkacjios** [comment]
Okay sweet, that will be helpful!

**Comment by bkacjios** [comment]
Mind giving this a try? I could only do so much testing with an 8bitdo controller, but I think I got everything. It will try to detect the boxx and read inputs from it.

[m-b0xx-x64 (dirty-1).zip](https://github.com/bkacjios/m-overlay/files/4670037/m-b0xx-x64.dirty-1.zip)

**Comment by IvantheTricourne** [comment]
@bkacjios 

Yo thanks for the quick turnaround!

Some things I noticed

- It seems that up/down are mixed up for both the analog stick and c-stick
- the mod buttons are being registered as "pressed" with just pure cardinal inputs (i.e., up/down register mod-y, left/right register mod-x)

**Comment by bkacjios** [comment]
Try this update.

I changed the background image to be the full transparent one, so all buttons will be transparent now. I flipped the up and down values to correct the flipped axis.

Lastly, I added some debug text at the bottom left of the screen for the joystick X and Y values. I think the values that DInput is giving me doesn't match the values in those gate images you sent earlier.

[m-b0xx-x64 (master-2).zip](https://github.com/bkacjios/m-overlay/files/4670422/m-b0xx-x64.master-2.zip)

Mind recording the values when you input pure cardinal inputs and when you use the modifier? That should help me fine tune the detection of the modifier buttons.

**Comment by IvantheTricourne** [comment]
The full transparency works now, and so do the detection for up/down.

Here's the values while pressing each of the mod buttons for each cardinal (each coord is (y,x)):

| dir |  Pure |  +Modx  |  +Mody |
|---|---|---|---|
| up |  0.631348,0 |  0.184296,0 | 0.466644,0  |
| down | -0.623566,0  | -0.176483,0  | -0.458832,0  |
| left |  0,-0.623566 | 0,-0.411774  |  0,-0.207855 |
| right | 0, 0.631348 | 0,0.419586  | 0,0.215668  |
| up+left |  0.631348,-0.623566 | 0.184296,-0.458832  |  0.466644,-0.176483 |
| up+right | 0.631348, 0.631348  |  0.184296,0.466644 |   0.466644, 0.184296 |
| down+left |  -0.623566,-0.623566 |  -0.176483,-0.458832 | -0.458832,-0.176483  |
| down+right | -0.623566, 0.631348 |  -0.176483,0.466644 | -0.458832,0.184296  |

Note, there are also shield tilt angles, which mess with these coordinates quite a bit (i.e., depending on when L or R are pressed). I will come back and post these in a bit.

**Comment by IvantheTricourne** [comment]
Shield Tilts with R:

| dir |  Pure |  +Modx  |  +Mody |
|---|---|---|---|
| up |  0.341156,0 |  same | same  |
| down | -0.333344,0 | same  | same  |
| left |  0,-0.396088 | same  |  same |
| right | 0, 0.403900 | same  | same  |
| up+left | 0.341156,-0.333344  | 0.239197,-0.396088  |  0.552917,-0.294128 |
| up+right | 0.341156, 0.341156  | 0.239197,0.403900  |  0.552917,0.301941  |
| down+left | -0.333344,-0.333344  |  -0.231384,-0.396088 | -0.529449,-0.309814  |
| down+right | -0.333344,0.341156 | -0.231384,0.403900  |  -0.529449,0.317627 |

**Comment by bkacjios** [comment]
[m-b0xx-x64 (master-3).zip](https://github.com/bkacjios/m-overlay/files/4670684/m-b0xx-x64.master-3.zip)

Alright.. Adjusted the values a bit to hopefully try and fit within those ranges.

**Comment by IvantheTricourne** [comment]
> [m-b0xx-x64 (master-3).zip](https://github.com/bkacjios/m-overlay/files/4670684/m-b0xx-x64.master-3.zip)
> 
> Alright.. Adjusted the values a bit to hopefully try and fit within those ranges.

It seems in some cases that the mod buttons are mixed (or in some cases both are pressed). Idk if you saw my second comment about shield tilts.

**Comment by bkacjios** [comment]
This is going to be a lot harder than I expected to detect the mod buttons. There's like way too many edge cases.

**Comment by IvantheTricourne** [comment]
Yeah, just seeing all these today myself lol... it's quite insane. There's actually even more angles available as well using C-stick lol

**Comment by bkacjios** [comment]
Well, I'm not sure if using DInput is going to be the right way to go about this. After doing a bit of searching, I found that the boxx has a serial port you can read from to read the raw button presses. I think switching to using serial will be the right way to go about this, but will require a bit more work. I would also have no way to test a system that uses serial, so it makes things even harder.

**Comment by IvantheTricourne** [comment]
@bkacjios

Please don't hesitate to let me know what you need in terms of testing. I'll be happy to help.

**Comment by bkacjios** [comment]
Well, I'll try to have something for you to test in the next few days.

**Comment by bkacjios** [comment]
Sorry, kinda forgot about this. I tried to get some form of serial port working, but it would really require a lot of work and energy which I don't have the patience for. Hate to say but I think this far out of the scope of this project.
