### ISSUE TITLE
[Suggestion] Add NTSC-J and PAL versions of Paper Mario: The Thousand-Year Door

### ISSUE THREAD

**Issue by Zephiles** [bkacjios/m-overlay#42]
I wasn't sure what to label this as, so I just labeled it as **suggestion**.

The NTSC-U version of the game is set to use `0x803CA398` as the address to get inputs from. The equivalent address for NTSC-J is `0x803C6818`, and the equivalent address for PAL is `0x803D63F8`. Both the NTSC-J and PAL versions of the game handle inputs the same way as the NTSC-U version, so it should be very simple to add support for them.

**Comment by bkacjios** [comment]
Sorry this took so long to get a release out.

https://github.com/bkacjios/m-overlay/releases/tag/1.4.5
