### ISSUE TITLE
How to find which stage is selected

### ISSUE THREAD

**Issue by exavadeathwitch** [bkacjios/m-overlay#43]
I was wondering what process you used to find which stage was being selected for melee slippi online. I'm modding a game called naruto storm 4 and I'm wondering how I could replicate your findings to help me mod the soundtrack for that game.

**Comment by bkacjios** [comment]
Melee is a fairly well documented game.

Pretty sure this is where I got the address for the stage I'd.

https://github.com/Achilles1515/20XX-Melee-Hack-Pack/blob/d179487818e5041aba18bf5a3cba3c2eab31a167/SSBM%20Facts.txt#L1979
