### ISSUE TITLE
[Request] Additional folder for All & add support for Trophy Tussle Stage

### ISSUE THREAD

**Issue by Carldacious** [bkacjios/m-overlay#52]
Both of my requests are in regards to the music aspect of m-overlay.

I wanted to see if were possible to add an 'All' folder within the Melee folder. This would cover both all stages and the menus. I like having various options for all stages (only) and menu (only) for control. I want that to stay! I just thought it would be cool to add this option so if there was a song you were really in the mood to hear, you could hear it everywhere!

The SD Remix version of Melee/Slippi modifies some stages and adds one in particular. The Trophy Tussle stage. I wanted to see if were possible to add support for this stage as it appears to have a completely different stage ID.

![image](https://user-images.githubusercontent.com/68999000/97586654-e329ee00-19d0-11eb-92d1-5ce5e203bd99.png)

Thanks again for your work on this project! It is seriously amazing!

**Comment by bkacjios** [comment]
I've actually been working on a major update to the music system. Trying to get it to work in all modes, from all-star, classic mode, training and versus. I should be able to include this stage too.

**Comment by Carldacious** [comment]
Thank you for all your hard work once again! This project is fantastic!

**Comment by bkacjios** [comment]
Mind trying out a little beta release for me? This should allow music to work in Training mode, all-star mode, and classic mode. Adventure still needs a bit of work, so I don't think it will play any music at the moment.

[m-overlay-x64 (master-153).zip](https://github.com/bkacjios/m-overlay/files/5461893/m-overlay-x64.master-153.zip)

I added the stages `Trophy Collection` and `All Star Rest Area` to the stages list, so those folders should show up in the Stage `Music folder`. These stages are marked as being part of the `Super Smash Bros` series, so any music in that series folder will also work for them.

**Comment by Carldacious** [comment]
Sure! Here are my notes!

**SD Remix:** 

Trophy Stage - Works! Uses both stage folder and series folder successfully!

**Classic Mode:** works! but....

No Music for:

Targets
Race to the Finish
Fan-Fares
Shooting game/Credits
Victory video/Congratulations!

Music starts immediately on Master Hand and doesn't react to his defeat 
_(I understand why this happens and do not think it's a big deal. However, I wonder if it's possible for it to react to this specific instance? Similar to how pausing the game brings the volume down?)_

**Adventure Mode:**

No Music for:

Stage Intro
Mushroom Kingdom
Peaches Castle
Kongo Jungle (Falls)
Jungle Japes
_Stopped here...._

**All Star:** 

Normal Stages work!

No Music for All Star Rest Area

**Training Mode:**

All stages work! Including Trophy Stage in SD Remix

**Comment by bkacjios** [comment]
Yeah, like I said adventure mode is incomplete for the moment. I have all the states mapped out, but I just need to apply it to the code now. I was thinking about making a new folder called `Single Player` that will contain all the stages for the adventure/classic mode like Mushroom Kingdom, Underground Caverns, break the targets, race to the finish, and all that. 

I might be able to fix master hand music, but no guarantees.

That's weird that the all-star rest area doesn't work. Will have to look into that.

Thanks for doing all that testing! I may have a new beta for you later today!

**Comment by Carldacious** [comment]
I understand. Just thought I would give it a go!

Adding a `Single Player` folder sounds perfect!

Totally get it about Master Hand.

My pleasure! Happy to help!

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-157).zip](https://github.com/bkacjios/m-overlay/files/5467217/m-overlay-x64.master-157.zip)

Here's another beta build.

* Music should work in all the "Special Melee" menus/modes now
* Renamed `All Star Rest Area` to `All-Star Rest Area`
* Fixed the `All-Star Rest Area` not playing music
* Fixed music sometimes playing for a brief moment when switching between game states
* Added `Break the Targets` to list of single player stages
* Added some of the event stages to list of single player stages
    * `Trophy Tussle - Entei`
    * `Trophy Tussle - Goomba`
    * `Trophy Tussle - Majora's Mask`
* Added `Home-Run Contest` to list of single player stages

I added the adventure mode only stages to the list of singleplayer stages, but they aren't actually used yet. Still need to sort that out since it's the most difficult.

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-158).zip](https://github.com/bkacjios/m-overlay/files/5467400/m-overlay-x64.master-158.zip)

Alrighty, I think this build should allow music to work in adventure mode now!

**Comment by Carldacious** [comment]
Would you like me to do any testing/provide feedback for the latest build? My apologies on the delay in response.

**Comment by bkacjios** [comment]
I did a lot of testing myself and did an official release! https://github.com/bkacjios/m-overlay/releases

**Comment by Carldacious** [comment]
I saw that! Great work! I will let you know if I notice anything! Feel free to reach out if I can be of any help! 

Once again, I super appreciate this project and everything it's about. It's so cool to play my favorite game ever with all of my favorite music. Thanks again!
