### ISSUE TITLE
Program crashes/stops responding when OBS tries to show it

### ISSUE THREAD

**Issue by jakobkg** [bkacjios/m-overlay#54]
**Describe the bug**
When OBS tries to show M'Overlay after having it hidden, M'Overlay consistently crashes. This happens if I'm showing M'Overlay, transition away and transition back to the scene M'Overlay is in, and it also happens if I simply add M'Overlay, toggle the source off and then back on again. This happens when sing the recommended setup where M'Overlay is captured using "game capture" regardless of other settings. The crash does not happen if M'Overlay is captured using a "Window Capture", but this setup does not allow transparency and has some other artifacts that are out of frame in the normal window. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OBS version: 26.0.2
 - M'Overlay version: 1.5.2, in Slippi mode

**To Reproduce**
1. Open OBS
2. Add M'Overlay as Game Capture source
3. Hide the source by clicking the eye icon or transitioning to a different scene
4. Show the source again by clicking the eye icon or transitioning back to the scene where M'Overlay is shown
5. M'Overlay crashes

**Debug console output**
The debug console does not show anything interesting when crashing, the crash occurs after the lines about `player.1.entity` and `player.2.entity`, before the line normally showing `match.playing = true` appears.

**Comment by jakobkg** [comment]
I just tested with M'Overlay v1.1.0 and the same crash occurs, so this issue is at least as old as Slippi mirroring/replay support

**Comment by bkacjios** [comment]
I can't seem to replicate this on my end with the latest OBS. What graphics card do you have? Maybe make sure you're on the latest drivers.

Do you have any programs that inject overlays into GPU accelerated applications, like MSI afterburner or anything of the sorts?

**Comment by jakobkg** [comment]
This is on a notebook GTX 1650 with the latest drivers and Windows update as of yesterday, with nothing like Steam, Afterburner, Discord or other things with overlays running. Is there a way I could get a more detailed crash dump to look at or add here?

**Comment by jakobkg** [comment]
Tested on my desktop computer and did not see the same crash. the environments are very similar so I'm kind of confused about what's happening

**Comment by bkacjios** [comment]
I'm not really sure to be honest. If it's silently crashing without a blue error screen it sounds like a problem that is out of my hands with the love2d engine. The only way to figure out what's going on is to attach a debugger to it.
