### ISSUE TITLE
run script on Linux without root 

### ISSUE THREAD

**Issue by wantija** [bkacjios/m-overlay#6]
run.sh requires 'sudo' access, if the script is modified to not use sudo it never hooks into dolphin. Here's the terminal output and it just repeats:
```
[DEBUG - 19:37:55] Created m-overlay config directory: /home/dan/.local/share/love/m-overlay

[INFO  - 19:37:55] Load: /home/dan/.local/share/love/m-overlay/clones.lua

[INFO  - 19:38:12] Hooked: Dolphin.exe

[DEBUG - 19:38:14] Gamecube memory found: 2300000000

[INFO  - 19:38:14] Watching process ram: Dolphin.exe

[INFO  - 19:38:14] Hooked: Dolphin.exe

[DEBUG - 19:38:14] Gamecube memory found: 2300000000

[INFO  - 19:38:14] Watching process ram: Dolphin.exe

[INFO  - 19:38:14] Hooked: Dolphin.exe
```

**Comment by bkacjios** [comment]
You need to give /usr/bin/love ptrace access with this command.

`sudo setcap cap_sys_ptrace=eip /usr/bin/love`

You won't need to run it as root after that.

**Comment by bkacjios** [comment]
I merged your pull request since you updated it! Also worth noting I added a permissions check to stop the program from going into a loop in 1e30e4329ba44a418d2497b3074af1c4f008a345
