### ISSUE TITLE
Add option to display Start button

### ISSUE THREAD

**Issue by ItsPepperpot** [bkacjios/m-overlay#61]
As of v1.6.0 the software no longer displays the Start button.
I appreciate that it usually is not relevant to normal gameplay, however, in some games, namely The SpongeBob SquarePants Movie, during speedruns there are certain tricks that require pressing the start button on certain frames.
In these instances it would be handy to see the start button, so it would be great if you could add the start menu back as a toggle.
Thanks again for the great software.

**Comment by bkacjios** [comment]
![New settings](https://i.imgur.com/z4P3DoK.png)

Added in latest release.

https://github.com/bkacjios/m-overlay/releases/tag/v1.6.4

**Comment by ItsPepperpot** [comment]
Awesome. Thank you! 👍
