### ISSUE TITLE
[Feature Request/Idea] Music probability 

### ISSUE THREAD

**Issue by Carldacious** [bkacjios/m-overlay#62]
Would it be possible to add the ability to influence how often a music track plays?

In order to avoid the need for a user interface, I had an idea. Would it be possible to add "_x" to the end of a file. X being a value between 0 and 100 for the likely-hood of how often a music track for a given stage/series will play? So for example "Menu01_90.flac" would play with a 90% likelihood. Would all tracks have to equal up to 100%? I am not sure the best way to implement this, but I wondered if it were possible.

As always, love this project and appreciate your hard work! Thanks!!!

**Comment by JordanLozinski** [comment]
Thinking of putting together a PR for this. My idea is that files that don't end with "_x" will default to a weight of 1. So a file with "_2" would be twice as likely as default tracks. This way, you don't have to annotate every single file to get this working.

Let me know if there's a nicer way to implement this.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.7.3

**Comment by Carldacious** [comment]
Love the update for a more GUI way of changing probability values! Very cool! Awesome work!

**I have a few questions about these changes:**

1. Does m-overlay still respect/implement weighing based on "_#" in file names or is that disabled now?

2. Is there any easy way to make probability configurations available in the GUI without being loaded in via dolphin where the files are in use? _(I can see that it is saving to probability.json so a work around is to follow formatting there and set values.)_

3. Would it be possible to allow different probability values per stage/area on a file instead of global values? I can see the pros and cons to either method. Just throwing the idea out there.


Thanks so much for your profound work on this project! I really love it! You never cease to amaze me!

**Comment by bkacjios** [comment]
>     1. Does m-overlay still respect/implement weighing based on "_#" in file names or is that disabled now?

Yes, it still uses this system. If you didn't configure that songs chance via the UI, it will use the _# as the initial value.

>     2. Is there any easy way to make probability configurations available in the GUI without being loaded in via dolphin where the files are in use? _(I can see that it is saving to probability.json so a work around is to follow formatting there and set values.)_

It's possible, it would just require a lot more work. It was just easier for me to use the current track-list for the given game state rather than creating a whole browser system.

>     3. Would it be possible to allow different probability values per stage/area on a file instead of global values? I can see the pros and cons to either method. Just throwing the idea out there.

This could be pretty easy to implement. I could just add a toggle between setting a "global" probability and a "stage" probability.

**Comment by Carldacious** [comment]
Awesome! Thank you for answering my questions!

> Yes, it still uses this system. If you didn't configure that songs chance via the UI, it will use the _# as the initial value.

So just to clarify, the number if using  "_#" should be a value between 0-100?

> It's possible, it would just require a lot more work. It was just easier for me to use the current track-list for the given game state rather than creating a whole browser system.

I understand! Makes sense to me!

> This could be pretty easy to implement. I could just add a toggle between setting a "global" probability and a "stage" probability.

Sweet! Happy to hear this is an easy implement.


Thanks again!

**Comment by bkacjios** [comment]
>So just to clarify, the number if using  "_#" should be a value between 0-100?

Yup. Technically it could go over 100, but it would just clamp it back down to 100.

**Comment by ribbanya** [comment]
Wait, what? I have hundreds of songs weighted using 1000 as a baseline (so a song with 500 would play half as much, and a song with 2000 would play twice as much).

When was this change made?

**Comment by bkacjios** [comment]
Okay so if you have a filename with _500 and _1000 it will still use those values internally. The issue is if you try to customize those files with the new UI, it will clamp it back to 0-100. 

```lua
if prob > 100 then
	log.warn("[MUSIC] Song %q has a probability greater than 100%", filepath)
end

music.PROBABILITY_SETTINGS["global"][filepath] = prob
```

**Comment by bkacjios** [comment]
Anyway. In the latest release I added a toggle for global/state based probability.

https://github.com/bkacjios/m-overlay/releases/tag/v2.0.2

**Comment by ribbanya** [comment]
> ```lua
> if prob > 100 then
> 	log.warn("[MUSIC] Song %q has a probability greater than 100%", filepath)
> end
> 
> music.PROBABILITY_SETTINGS["global"][filepath] = prob
> ```

Is there a use case where that warning would indicate something unexpected? If someone is using the GUI, it can never happen, and if they aren't, shouldn't they be aware of what the probabilities are?

**Comment by bkacjios** [comment]
It's just for sanity sake. If someone starts to use the UI after having a file with a file probability >100 and they start to wonder why it's being clamped, the debug console will at least provide some information if they go looking for it.

**Comment by ribbanya** [comment]
I see. I'm just wondering because in my case, it's going to print at least 50 warnings every scene change
