### ISSUE TITLE
Full Music Support for Slippi?

### ISSUE THREAD

**Issue by zackarhino** [bkacjios/m-overlay#64]
Not sure if this is currently possible but it would be nice to be able to change all of the slippi music, like the title screen.

I know it's a minor thing but I would enjoy being able to hear it when playing melee rollback.

**Comment by bkacjios** [comment]
I'm not sure what you're asking. This already supports music on the menu's and such. Music doesn't play on the title screen though, just like vanilla melee.

**Comment by zackarhino** [comment]
Sorry, I was talking about like the intro movie. I've been adding all the tracks over the past half hour or so and I also noticed there's also none of the little sound clips and stuff, like the intro clip for adventure/classic mode.

Again, it's a very minor thing but I would love to be able to have the full melee experience in slippi. But then again, maybe I should just play vanilla melee lol
