### ISSUE TITLE
Triggers don't show as seperate when in replay/mirror mode

### ISSUE THREAD

**Issue by jjslid3r** [bkacjios/m-overlay#65]
**Describe the bug**
The triggers only show as one trigger when in replay/mirror mode. When watching back my slippi replays it makes it hard to tell which trigger is being pressed exactly

**Desktop:**
 - OS: Windows 10
 - Dolphin Version: Slippi 2.2.3

**To Reproduce**
1. Open replay in Slippi Desktop App
2. Open M'Overlay and set it to replay/mirror mode
3. See that both triggers are now on top of each other

**Expected behavior**
I'm not sure if this is an intended feature or not, but I assume the triggers should normally be separate as they are in Rollback/Netplay mode.

**Screenshots**
![moverlay](https://user-images.githubusercontent.com/40483010/104110929-943ee580-52aa-11eb-8282-c6b38412c8b2.png)

**Comment by bkacjios** [comment]
Not a bug. Replays don't have the data for both.

See `0x29` in https://github.com/project-slippi/slippi-wiki/blob/master/SPEC.md#pre-frame-update
