### ISSUE TITLE
Support for Donald Duck Goin' Quackers

### ISSUE THREAD

**Issue by AntiquaEmblem** [bkacjios/m-overlay#68]
As someone interested in Speedrunning, being able to use this on Donald Duck Goin' Quackers for Gamecube would be super convenient and contribute to my ability to practice and record runs. Thanks for your hard work, I love using this program

**Comment by bkacjios** [comment]
Added in latest release: https://github.com/bkacjios/m-overlay/releases/tag/v1.6.6
