### ISSUE TITLE
No longer hooks into Linux Slippi Appimage

### ISSUE THREAD

**Issue by FireStarW** [bkacjios/m-overlay#69]
**Describe the bug**
m-overlay no longer hooks into the latest Slippi Appimage for Linux, it seems the process name for the launched Dolphin has changed, from the expected `AppRun` , to `Apprun.wrapped` , shown by the two below comparison images from Gnome System Monitor, of both before (_Slippi 2.2.3 Appimage_ ) and now (_Slippi 2.2.4 Appimage_).

**Slippi 2.2.3:**
![Screenshot from 2021-01-20 00-10-43](https://user-images.githubusercontent.com/11762725/105130195-8e1fe480-5ab4-11eb-8132-ea91547bb666.png)

**Slippi 2.2.4:**
![Screenshot from 2021-01-20 00-10-59](https://user-images.githubusercontent.com/11762725/105130241-a7c12c00-5ab4-11eb-8e9c-b5cf46ac8b99.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Dolphin Version: Slippi 2.2.4

**Comment by bkacjios** [comment]
Mind giving this a try since I can't access my Linux partition atm? Just remove the .zip in the file name. 

[m-overlay-x64 (master-222).love.zip](https://github.com/bkacjios/m-overlay/files/5840360/m-overlay-x64.master-222.love.zip)

**Comment by FireStarW** [comment]
I can confirm this does work now:
![Screenshot from 2021-01-20 09-58-29](https://user-images.githubusercontent.com/11762725/105192489-27c3b200-5b06-11eb-9fff-f942e03c3671.png)

**Comment by bkacjios** [comment]
Thanks. I updated the file in the release to that build.
