### ISSUE TITLE
Support for Twilight Princess and Mario Sunshine ?

### ISSUE THREAD

**Issue by maranedah** [bkacjios/m-overlay#7]
Hey! I'm looking for a way to show my controller inputs on Twilight Princess runs and Mario Sunshine. It is possible to add support for those games? Thanks in advance !

**Comment by bkacjios** [comment]
Shouldn't be too hard. Any specific versions of each game?

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.0.1

Well, here you go. Luckily I had these games! These are all for the original revision of the game and I'm not sure if there are other revisions.

**Comment by maranedah** [comment]
Wow that was fast, thanks a lot ! I didn't specify the versions, but I was thinking on the GC version of Twilight Princess (don't know if there's different versions of the game), could you add it too please?

**Comment by bkacjios** [comment]
I added both GC and Wii version support for Twilight Princess
