### ISSUE TITLE
[Feature Request] Support for 𝗧𝗵𝗲 𝗔𝗸𝗮𝗻𝗲𝗶𝗮 𝗕𝘂𝗶𝗹𝗱 Stages

### ISSUE THREAD

**Issue by Carldacious** [bkacjios/m-overlay#70]
I was hoping that we may see support for this special modification of Melee. 

Currently they have added back most N64 stages. Is there any way we can get specific folders to support these stages as well?

𝗧𝗵𝗲 𝗔𝗸𝗮𝗻𝗲𝗶𝗮 𝗕𝘂𝗶𝗹𝗱: https://github.com/akaneia/akaneia-build

https://youtu.be/Hvj4QGQ0TQM

**Comment by bkacjios** [comment]
Done: https://github.com/bkacjios/m-overlay/releases/tag/v1.6.7
