### ISSUE TITLE
[Request] Native Overlay without OBS

### ISSUE THREAD

**Issue by Gruntled173** [bkacjios/m-overlay#74]
I don't stream often on OBS, but I like to stream Melee to my friends via Discord when I am playing. It would be great if the overlay could natively appear on top of the Dolphin window without any additional recording software, similar to how Discord already uses its gaming overlay.

**Comment by bkacjios** [comment]
This isn't something I could do atm. That would require injecting into dolphin itself and rendering on the program itself. Doing that and supporting all the different rendering engines would be a difficult task. Plus, you could just set your overlay to show your opponents inputs and be used as a cheat. So I'm sorry, but I'm not going to do this.
