### ISSUE TITLE
Overlay displaying red error symbol, suddenly not working when it was working prior

### ISSUE THREAD

**Issue by higps** [bkacjios/m-overlay#79]
**Describe the bug**
Overlay doesn't work (it used to) and just shows error with red symbol on it

**Desktop (please complete the following information):**

 - OS: Win 10
 - Dolphin Version: Slippi 2.2.5

**To Reproduce**
1. Open Game
2. Open overlay

**Expected behavior**
Inputs should be shown, this used to work, no changes made on my end, now it suddenly doesn't work.

**Screenshots**
![m-overlay-64_2021-03-30_21-23-28](https://user-images.githubusercontent.com/59850204/113045130-befc5400-919e-11eb-8936-19180b2f0aed.png)

**Debug console output**
```
[INFO  - 21:30:21] [DOLPHIN] Hooked
[INFO  - 21:30:22] [DOLPHIN] Watching ram: 7FFF0000 [2000000]
[DEBUG - 21:30:22] [DOLPHIN] Game: GALE01 revision 2
[INFO  - 21:30:22] [DOLPHIN] Loaded game config: GALE01-2
[INFO  - 21:30:22] [MEMORY] Mapping game memory..
[DEBUG - 21:30:22] [MEMORY] [0x8046B6AE  = 0x00000000] match.finished = false
[DEBUG - 21:30:22] [MEMORY] [0x80479D30  = 0x00000001] menu.major = 1
[DEBUG - 21:30:22] [MEMORY] [0x8046B6A5  = 0x00000000] match.playing = false
[DEBUG - 21:30:35] [MEMORY] [0x80479D30  = 0x0000001C] menu.major = 28
[DEBUG - 21:30:35] [MEMORY] [0x804D6598  = 0x00000003] menu.player_one_port = 3
[DEBUG - 21:30:35] [MEMORY] [0x804A0BC0 -> 0xFFFFFFFF811003C0] player.1.cursor -> 0xFFFFFFFF811003C0
[DEBUG - 21:30:42] [MEMORY] [0x80479D33  = 0x00000001] menu.minor = 1
[DEBUG - 21:30:47] [MEMORY] [0x80479D33  = 0x00000002] menu.minor = 2
[DEBUG - 21:30:47] [MEMORY] [0x8049E753  = 0x00000025] stage = 37
[DEBUG - 21:30:47] [MEMORY] [0x80453130 -> 0xFFFFFFFF80C6B9A0] player.1.entity -> 0xFFFFFFFF80C6B9A0
[DEBUG - 21:30:47] [MEMORY] [0x80453FC0 -> 0xFFFFFFFF80CAAA60] player.2.entity -> 0xFFFFFFFF80CAAA60
[DEBUG - 21:30:48] [MEMORY] [0x8046B6A5  = 0x00000001] match.playing = true

```
**Additional context**

**Comment by bkacjios** [comment]
The red error means the controller is disconnected for that port that is currently being displayed.

You can change what port is being displayed by using the scrollwheel or pressing 1-4 on the keyboard/numpad.

You can also try this new update I literally just released.

https://github.com/bkacjios/m-overlay/releases/tag/v1.7.1
