### ISSUE TITLE
Support pointers

### ISSUE THREAD

**Issue by EthanArmbrust** [bkacjios/m-overlay#8]
I'm not sure if this applies to other games, but for Metroid Prime the location of the joker code for the controller in memory is volatile, and can change after resetting the game.
For Metroid Prime v1.0, the pointer should be located at 0x804576FC with the joker code being located at the value of the pointer with an offset of 0x04.

**Comment by bkacjios** [comment]
What exactly is a joker code?

**Comment by EthanArmbrust** [comment]
Its just the way the controller input is stored in memory. Eg A = 1, B = 2, X = 4.  I'm not sure if that's the proper term for it, but that's how it was described to me.

**Comment by bkacjios** [comment]
Alright, well if it's a pointer, that's pretty easy to handle I think. I'll investigate.

**Comment by bkacjios** [comment]
Also, what version is the address `0x804576FC` for? I only have version 2 of the game.

**Comment by EthanArmbrust** [comment]
Its for v1.00

**Comment by bkacjios** [comment]
Alright, well I'll have to find a rom of that version before I can test. My memory watcher library already supports pointers, so it should be pretty easy.

**Comment by bkacjios** [comment]
![Working pointers!](https://i.imgur.com/EeMsgaa.png)

I think I got this working.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.0.2

**Comment by EthanArmbrust** [comment]
Works great on 1.00. Thanks!
