### ISSUE TITLE
[Game Request] Add support for Pikmin 251

### ISSUE THREAD

**Issue by Storyshiftfanboy** [bkacjios/m-overlay#81]
Hi! It's my first time here, and I was wondering if you could add support for Pikmin 251 (A Pikmin 2 mod). I'd love to play it with this overlay, it's just not supported, even though it plays just like Pikmin 2.

**Comment by bkacjios** [comment]
If it's a "clone" aka mod of Pikmin 2, you can try to create a `clones.lua` file in the config directory. This can be accessed by pressing escape and pressing the `open config directory` button on the bottom left.

```lua
["CLONED GAME ID"] = {
	[0] = { id = "GPVE01", version = 0 }
}
```

Replace "CLONED GAME ID" with the ID of the mod.

**Comment by bkacjios** [comment]
https://github.com/bkacjios/m-overlay/releases/tag/v1.7.2
