### ISSUE TITLE
Crashing after a few matches

### ISSUE THREAD

**Issue by joe564338** [bkacjios/m-overlay#84]
So after playing a few matches in slippi m overlay just crashes. It just exits out. No error message. Not sure what could be the problem.
OS: Windows
Slippi: 2.2.6

**Comment by buvk** [comment]
I am also having this issue.  Were you able to solve your problem?

**Comment by joe564338** [comment]
Get latest fixes it
https://github.com/bkacjios/m-overlay/releases/tag/v1.7.2

**Comment by buvk** [comment]
Ah I already have the latest version. Unfortunately it still crashes for me.
