### ISSUE TITLE
When I press open config directory, it never opens anything for me.

### ISSUE THREAD

**Issue by JoshoShow** [bkacjios/m-overlay#88]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Dolphin Version: [e.g. Slippi 2.2.1]

**To Reproduce**
1. Open game '....'

**Expected behavior**

**Screenshots**

**Debug console output**
```
Open the settings menu by pressing the escape key on your keyboard.
Check 'Debug console' and copy/paste the output from it here when replicating your issue.
```
**Additional context**

**Comment by bkacjios** [comment]
I guess you figured this out seeing you closed the issue?
