### ISSUE TITLE
[REQUEST] Support for Metal Gear Solid: The Twin Snakes

### ISSUE THREAD

**Issue by spenito76** [bkacjios/m-overlay#90]
This game is gaining some traction in the speedrunning scene and I think it would be great to have a working overlay to help new players and fans alike better understand what's happening in runs. Something important to note is that for the sake of the Psycho Mantis fight, TTS runners map both P1 and P4 to the same controller to remove the need to manually swap ports mid fight. I may look into implementing this myself however I figured I'd open up the request in case someone more experienced than myself would like to take on this task.

**Comment by bkacjios** [comment]
I'll take a look into it! Do you know if there's multiple revisions of this game, and if so, what version does the speedrunning community use?

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-280).zip](https://github.com/bkacjios/m-overlay/files/6667371/m-overlay-x64.master-280.zip)

So I got it working. The only thing is I'm not sure if this would break or not when switching to disk 2.

**Comment by bkacjios** [comment]
Ended up finding a save file towards the end of the game to make sure it still works past disk 1 and it does.

https://github.com/bkacjios/m-overlay/releases/tag/v1.7.6b
