### ISSUE TITLE
Remap music folder?

### ISSUE THREAD

**Issue by ribbanya** [bkacjios/m-overlay#94]
Is there a setting to remap the music directory location to somewhere else? I'd like to use a different drive for the music.

I can just use a junction, but native support would be useful.

**Comment by bkacjios** [comment]
Sadly no, at least not easily. Love2D limits its filesystem write permissions to its "save directory" which is in the appdata folder, so it wouldn't be able to create the folder structure anywhere else.

I could probably get around this, but it would require some work. I'll look into it, but no promises. Symlinks are always an option too.

**Comment by ribbanya** [comment]
Thanks for the response.

Closing this because my question was answered and a junction serves the same purpose. Feel free to reopen if you want to pursue it.
