### ISSUE TITLE
Music only looping 4 tracks

### ISSUE THREAD

**Issue by Zerks** [bkacjios/m-overlay#96]
Hey, love M'Overlay but I'm trying to add music to places like the menu, and I get this bug:

[ERROR - 14:46:12] [MEMORY] hook error: Melee - Menu state (music.lua:365: attempt to index local 'info' (a nil value)
stack traceback:
        music.lua:365: in function 'loadStageMusicInDir'
        music.lua:418: in function 'loadForStage'
        music.lua:289: in function <music.lua:287>
        [C]: in function 'xpcall'
        modules/memory/init.lua:634: in function 'runhook'
        modules/memory/init.lua:617: in function 'runhooks'
        modules/memory/init.lua:559: in function 'update'
        main.lua:199: in function 'update'
        main.lua:587: in function <main.lua:567>
        [C]: in function 'xpcall'
        [string "boot.lua"]:802: in function <[string "boot.lua"]:769>)

It only now loops the first 4 songs on my list, similarly any music I add to the beyond melee folders just don't play, not sure what's wrong. Any idea how to fix it?

**Comment by bkacjios** [comment]
Looks like one of your files may be corrupted and it's unable to get the file information. I fixed this from erroring and had it print out a warning in the debug console.

[m-overlay-x64 (master-302).zip](https://github.com/bkacjios/m-overlay/files/6873024/m-overlay-x64.master-302.zip)

Mind giving this standalone build a try to see if it fixes your issue? If it does I'll push out a full release with installer.

**Comment by bkacjios** [comment]
I'm going to just assume this fixes the issue then
