### ISSUE TITLE
MacOS via Love running, but not functioning

### ISSUE THREAD

**Issue by divuyes** [bkacjios/m-overlay#97]
**Describe the bug**
Unlike the only other bug report about running on Mac, my M'Overlay actually runs. It shows the "Waiting for dolphin..." animation and dialogue, as well as the "Waiting for melee..." animation and dialogue when Dolphin is run. However, when Melee is opened, it still says "Waiting for melee..." and it doesn't detect it no matter what I do. I have a hunch that this might be a permissions issue within Big Sur, however I am not entirely sure that is the case, and I do not know how to solve this.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.4
 - Dolphin Version: Slippi 2.3.1

**To Reproduce**
1. Open the m-overlay.love file
2. Open Dolphin
3. Load Melee

**Expected behavior**
I expected it to detect Melee since it detected Dolphin, however it didn't do anything and kept waiting for Melee.

**Screenshots**
Initial run:
<img width="512" alt="Screen Shot 2021-07-28 at 7 05 50 PM" src="https://user-images.githubusercontent.com/47830555/127411682-6c2f68a5-aaad-4e05-ad75-5a6801f6d64f.png">
Opening Slippi through Slippi Launcher:
<img width="1050" alt="Screen Shot 2021-07-28 at 7 06 50 PM" src="https://user-images.githubusercontent.com/47830555/127411718-8ce8dbb2-e9c8-4766-83ba-85d69e12e108.png">
As shown, Melee is running however not being detected, despite Dolphin being hooked.

Settings (in case it's useful):
<img width="513" alt="Screen Shot 2021-07-28 at 7 09 24 PM" src="https://user-images.githubusercontent.com/47830555/127411852-30ec59fb-c0d5-4144-9637-f7795172860d.png">

**Debug console output**
```
[INFO  - 19:05:43] [DOLPHIN] Unhooked
[DEBUG - 19:06:02] Found dolphin-emu process: /proc/32757
[INFO  - 19:06:02] [DOLPHIN] Hooked
[INFO  - 19:06:04] [DOLPHIN] Unhooked
[DEBUG - 19:06:07] Found dolphin-emu process: /proc/32764
[INFO  - 19:06:07] [DOLPHIN] Hooked
```

**Comment by bkacjios** [comment]
Yeah, MacOS functionality is currently incomplete, it's why I don't have an official dmg release of it yet. I actually built a hackintosh using my old PC parts to try and work on development for it and the most I managed to do was find the dolphin process, which is the behavior you are currently seeing.

https://github.com/bkacjios/m-overlay/blob/master/source/modules/memory/osx.lua

I hit a roadblock when I found that applications on mac need a special permission called [Debugging Tool Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_debugger) in order to attach to it and read from the processes memory.

If you or anyone else knows more about macs and could help with this, I'd really appreciate it.

**Comment by divuyes** [comment]
Hmm. I don't know a whole lot about developing for Lua/MacOS directly, it seems like this is a part of Hardened Runtime. Is it possible to go in Xcode and grant this entitlement?

**Comment by bkacjios** [comment]
I have no idea. I basically no nothing about mac. Even if you did grant the permissions somehow, the osx bit of code is incomplete. It would allow me to work on it again though.

**Comment by divuyes** [comment]
When I can, I'll see if I can use Xcode to modify the entitlement permissions of it. I'm not quite sure if I can because I don't know if Xcode works with programs other than .apps, but we will see. If not, then the .love file may be able to work if converted into a .app. We shall see.

**Comment by bkacjios** [comment]
[m-overlay-x64 (master-305).zip](https://github.com/bkacjios/m-overlay/files/6897417/m-overlay-x64.master-305.zip)

I made a build with extra prints to output in the terminal if it managed to get the correct permissions or not. Rename it from .zip to .love

But just so you know, M'Overlay still won't work no matter what you do, but this information would help knowing I can actually properly hook and read from memory.

**Comment by divuyes** [comment]
As expected, the new patch printed failed permissions. However, I may have found what you need to do. First, it needs to be a .app file, so I cannot do anything with the current .love file. However, once you get that, you can follow [this article](https://wiki.lazarus.freepascal.org/Hardened_runtime_for_macOSl) to enable the Hardened Runtime and grant Debugging Tool Entitlement. Obviously, any time it says in the article the camera permission, substitute it with `com.apple.security.cs.debugger`.

**Comment by bkacjios** [comment]
I wonder if this would work on the love.app, since basically, it's the engine in which m-overlay runs? I'll have to get my hackintosh working again to try and start work on this again.

**Comment by bkacjios** [comment]
Okay so after some more research, I found that the application you want to read memory from ALSO needs a seperate permissions set.

`com.apple.security.get-task-allow`

So this would also have to be set on dolphin as well..

**Comment by bkacjios** [comment]
Well, from what I'm reading, this would require me to have a development ID, which I don't have, in order to sign my own application. This would be a huge roadblock, since I don't think they accept apps with these debug permissions set.

As much as I would love to have support for mac, it just seems like it's impossible to do so.

**Comment by divuyes** [comment]
Oh alright. If anything changes, I'll make a new thread. However, since the future is grim, I'm gonna close this thread. Thanks for trying, at least.
