### ISSUE TITLE
Mario Kart Wii custom track distribution with custom music

### ISSUE THREAD

**Issue by Sidilium** [bkacjios/m-overlay#98]
Mario Kart Wii has lots of Custom Track Distributions that could use more music variety, they are limited by the amount of track music in the game. Is it possible to link the music with the courses using M'Overlay like in Slippi Melee? I tried disabling the track music using a Gecko Code, and then using YouTube to play track music, but it interrupts the game too much.

**Comment by bkacjios** [comment]
It's possible. I'm not really into mario kart though so someone else would have to take on the task of finding the memory values that correlate with stage IDs and the menu states.
